name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
scope = "leanprover"
name = "«doc-gen4»"
rev = "689fdeecf45e08cc048214680d40cfe2491be78b"

[[require]]
name = "Project"
path = "../programs/lean"
