import Project.ByteEcho.Spec
import Project.Mergesort.Contracts

/-!
# Contracts for the generated byte-echo wrapper

The generated program has a deliberately small reachable call graph: the
allocator is called once for a one-byte buffer, then the read and write shims
forward to the two `stdio` imports.  These contracts use the same
continuation-passing shape as the GCD stream example.
-/

namespace Project.ByteEcho.Contracts

open Wasm
open Iris Iris.ProgramLogic Language.Notation Std
open Wasm.SepLogic Wasm.SmallStep
open scoped Wasm.SmallStep.Outcome

abbrev HeapIProp := IProp (WasmHeapGF Universal.State)

abbrev callExpr := Project.Mergesort.Contracts.callExpr
abbrev resumeExpr := Project.Mergesort.Contracts.resumeExpr

def ResumeWP [WasmSmallStepGS hlc Universal.State]
    (results : List Value)
    (callerLocals : Locals) (stack : List Value)
    (code : Program) (arity : Nat) (remainder : List Value)
    (controls : List ControlFrame) (calls : List CallFrame)
    (s : Stuckness) (E : CoPset)
    (Phi : ObservableOutcome → HeapIProp) : HeapIProp :=
  WP (resumeExpr results callerLocals stack code arity remainder controls calls)
    @ s; E [{ Phi }]

def CallContract [WasmSmallStepGS hlc Universal.State]
    (absoluteIndex : Nat) (operands : List Value)
    (callerLocals : Locals) (stack : List Value)
    (code : Program) (arity : Nat) (remainder : List Value)
    (controls : List ControlFrame) (calls : List CallFrame)
    (s : Stuckness) (E : CoPset)
    (Phi : ObservableOutcome → HeapIProp)
    (resources : HeapIProp) : Prop :=
  resources ⊢ WP (callExpr absoluteIndex operands callerLocals stack code arity
    remainder controls calls) @ s; E [{ Phi }]

def ByteSlice [WasmHeapGS Universal.State]
    (base : UInt32) (bytes : List UInt8) : HeapIProp :=
  Project.Mergesort.Representations.ByteSlice base bytes

def Streams [WasmHostStateGS Universal.State]
    (input output : List UInt8) (raised : Bool) : HeapIProp :=
  Project.Mergesort.Representations.Streams input output raised

def RuntimeContext [WasmSmallStepGS hlc Universal.State] : HeapIProp := iprop(
  runtimeModuleOwn ⟨0⟩ Project.ByteEcho.module ∗
  hostEnvOwn 0 (Universal.envFor Project.ByteEcho.module))

def allocatorCursor : UInt32 := 1048576
def heapBase : UInt32 := 1048592
def allocatedFinish : UInt32 := 1048593

def readContractAt [WasmSmallStepGS hlc Universal.State]
    (absoluteIndex : Nat)
    (operands : UInt32 → UInt32 → List Value) : Prop :=
  ∀ (ptr requested : UInt32) (buffer input output : List UInt8)
    (raised : Bool)
    {callerLocals : Locals} {stack : List Value}
    {code : Program} {arity : Nat} {remainder : List Value}
    {controls : List ControlFrame} {calls : List CallFrame}
    {s : Stuckness} {E : CoPset}
    {Phi : ObservableOutcome → HeapIProp},
    let count := min requested.toNat input.length
    CallContract absoluteIndex (operands ptr requested)
      callerLocals stack code arity remainder controls calls s E Phi iprop(
        RuntimeContext ∗ Streams input output raised ∗ ByteSlice ptr buffer ∗
        ⌜requested.toNat = buffer.length ∧ 0 < requested.toNat⌝ ∗
        (RuntimeContext -∗ Streams (input.drop count) output raised -∗
          ByteSlice ptr (input.take count ++ buffer.drop count) -∗
          ⌜count ≤ requested.toNat⌝ -∗
          ResumeWP [.i32 (UInt32.ofNat count)] callerLocals stack code arity
            remainder controls calls s E Phi))

def writeContractAt [WasmSmallStepGS hlc Universal.State]
    (absoluteIndex : Nat)
    (operands : UInt32 → UInt32 → List Value) : Prop :=
  ∀ (ptr requested : UInt32) (bytes input output : List UInt8)
    (raised : Bool)
    {callerLocals : Locals} {stack : List Value}
    {code : Program} {arity : Nat} {remainder : List Value}
    {controls : List ControlFrame} {calls : List CallFrame}
    {s : Stuckness} {E : CoPset}
    {Phi : ObservableOutcome → HeapIProp},
    CallContract absoluteIndex (operands ptr requested)
      callerLocals stack code arity remainder controls calls s E Phi iprop(
        RuntimeContext ∗ Streams input output raised ∗ ByteSlice ptr bytes ∗
        ⌜requested.toNat = bytes.length ∧ 0 < requested.toNat⌝ ∗
        (RuntimeContext -∗ Streams input (output ++ bytes) raised -∗
          ByteSlice ptr bytes -∗
          ResumeWP [] callerLocals stack code arity remainder controls calls
            s E Phi))

def Import0Spec [WasmSmallStepGS hlc Universal.State] : Prop :=
  readContractAt (hlc := hlc) 0
    (fun ptr requested => [.i32 ptr, .i32 requested])

def Import1Spec [WasmSmallStepGS hlc Universal.State] : Prop :=
  writeContractAt (hlc := hlc) 1
    (fun ptr requested => [.i32 ptr, .i32 requested])

/-- Local `func5`, absolute index 8: the generated read shim. -/
def Func5Spec [WasmSmallStepGS hlc Universal.State] : Prop :=
  readContractAt (hlc := hlc) 8
    (fun ptr requested => [.i32 requested, .i32 ptr])

/-- Local `func6`, absolute index 9: the generated write shim. -/
def Func6Spec [WasmSmallStepGS hlc Universal.State] : Prop :=
  writeContractAt (hlc := hlc) 9
    (fun ptr requested => [.i32 requested, .i32 ptr])

end Project.ByteEcho.Contracts
