/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.RustArrayTests

open Wasm

def func0 : Wasm.Program :=
  [
  .localGet 1,
  .localGet 2,
  .add,
  .ret
]

def func0Def : Wasm.Function :=
  { params := [.i32, .i32, .i32], locals := [], body := func0, results := [.i32] }

def func1 : Wasm.Program :=
  [
  .localGet 1,
  .const (1 : UInt32),
  .add,
  .ret
]

def func1Def : Wasm.Function :=
  { params := [.i32, .i32], locals := [], body := func1, results := [.i32] }

def func2 : Wasm.Program :=
  [
  .localGet 0,
  .localGet 1,
  .call 3,
  .const (1 : UInt32),
  .and,
  .localGet 2,
  .xor,
  .ret
]

def func2Def : Wasm.Function :=
  { params := [.i32, .i32, .i32], locals := [], body := func2, results := [.i32] }

def func3 : Wasm.Program :=
  [
  .localGet 1,
  .const (0 : UInt32),
  .eq,
  .const (1 : UInt32),
  .and,
  .ret
]

def func3Def : Wasm.Function :=
  { params := [.i32, .i32], locals := [], body := func3, results := [.i32] }

def func4 : Wasm.Program :=
  [
  .localGet 0,
  .localGet 1,
  .call 3,
  .const (1 : UInt32),
  .and,
  .const (3 : UInt32),
  .add,
  .ret
]

def func4Def : Wasm.Function :=
  { params := [.i32, .i32], locals := [], body := func4, results := [.i32] }

/-- export: empty_plus_three -/
def func5 : Wasm.Program :=
  [
  .localGet 0,
  .load32 (0 : UInt32),
  .localGet 0,
  .load32 (4 : UInt32),
  .call 4,
  .ret
]

def func5Def : Wasm.Function :=
  { params := [.i32], locals := [], body := func5, results := [.i32] }

/-- export: empty_xor_flag -/
def func6 : Wasm.Program :=
  [
  .localGet 0,
  .load32 (0 : UInt32),
  .localGet 0,
  .load32 (4 : UInt32),
  .localGet 1,
  .call 2,
  .ret
]

def func6Def : Wasm.Function :=
  { params := [.i32, .i32], locals := [], body := func6, results := [.i32] }

/-- export: len_plus_arg -/
def func7 : Wasm.Program :=
  [
  .localGet 0,
  .load32 (0 : UInt32),
  .localGet 0,
  .load32 (4 : UInt32),
  .localGet 1,
  .call 0,
  .ret
]

def func7Def : Wasm.Function :=
  { params := [.i32, .i32], locals := [], body := func7, results := [.i32] }

/-- export: len_plus_one -/
def func8 : Wasm.Program :=
  [
  .localGet 0,
  .load32 (0 : UInt32),
  .localGet 0,
  .load32 (4 : UInt32),
  .call 1,
  .ret
]

def func8Def : Wasm.Function :=
  { params := [.i32], locals := [], body := func8, results := [.i32] }

def «module» : Wasm.Module :=
{
  imports := [],
  funcs := [
    func0Def,
    func1Def,
    func2Def,
    func3Def,
    func4Def,
    func5Def,
    func6Def,
    func7Def,
    func8Def
  ],
  exports := [
    { name := "empty_plus_three", funcIdx := 5 },
    { name := "empty_xor_flag", funcIdx := 6 },
    { name := "len_plus_arg", funcIdx := 7 },
    { name := "len_plus_one", funcIdx := 8 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1048576 : UInt32) }
  ],
  types := [
    { params := [.i32, .i32, .i32], results := [.i32] },
    { params := [.i32, .i32], results := [.i32] },
    { params := [.i32], results := [.i32] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.RustArrayTests
