/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.NearFlag

open Wasm

def func0 : Wasm.Program :=
  [
  .constI64 (8 : UInt64),
  .const (1048576 : UInt32),
  .extendUI32,
  .call 0,
  .constI64 (4 : UInt64),
  .const (1048584 : UInt32),
  .extendUI32,
  .constI64 (1 : UInt64),
  .const (1048588 : UInt32),
  .extendUI32,
  .constI64 (18446744073709551615 : UInt64),
  .call 1,
  .drop
]

def func0Def : Wasm.Function :=
  { params := [], locals := [], body := func0, results := [] }

def «module» : Wasm.Module :=
{
  imports := [
    { «module» := "env", name := "log_utf8", params := [.i64, .i64], results := [] },
    { «module» := "env", name := "storage_write", params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] }
  ],
  funcs := [
    func0Def
  ],
  exports := [
    { name := "set_flag", funcIdx := 2 }
  ],
  memory := some { pagesMin := (17 : UInt32), pagesMax := none, data := [
    { offset := some (1048576 : UInt32), bytes := [(102 : UInt8), (108 : UInt8), (97 : UInt8), (103 : UInt8), (32 : UInt8), (115 : UInt8), (101 : UInt8), (116 : UInt8), (102 : UInt8), (108 : UInt8), (97 : UInt8), (103 : UInt8), (1 : UInt8)] }
  ] },
  globals := [
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1048589 : UInt32) },
    { init := .i32 (1048592 : UInt32) }
  ],
  types := [
    { params := [.i64, .i64], results := [] },
    { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
    { params := [], results := [] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.NearFlag
