import Project.Mergesort.RangeProof

/-!
# Exact contract for the generated byte-to-digit helper

`func52` implements the successful numeric-byte branch of Rust's internal
radix decoder.  It returns a two-word option-like descriptor `(1, digit)`.
-/

namespace Project.Mergesort.ParseByteProof

open Wasm
open Iris Iris.ProgramLogic Language.Notation Std
open Wasm.SepLogic Wasm.SmallStep
open Project.Mergesort.FunctionSpecs
open Project.Mergesort.Machine
open Project.Mergesort.RangeProof

private theorem twp_geU
    [WasmSmallStepGS hlc]
    {s : Stuckness} {E : CoPset}
    {Φ : List Value → IProp WasmHeapGF}
    {params localValues values : List Value}
    {lhs rhs result : UInt32} {code : Program} {arity : Nat}
    {remainder : List Value} {controls : List ControlFrame}
    {calls : List CallFrame}
    (hresult : result = if lhs ≥ rhs then 1 else 0) :
    WP (.running
      ⟨⟨params, localValues, .i32 result :: values⟩,
        code, arity, remainder, controls, calls⟩ : Expr α) @ s; E [{ Φ }] ⊢
    WP (.running
      ⟨⟨params, localValues, .i32 rhs :: .i32 lhs :: values⟩,
        .geU :: code, arity, remainder, controls, calls⟩ : Expr α)
      @ s; E [{ Φ }] :=
  twp_pureStep _ _ _ (fun _ => Step.geU hresult)

private theorem slotFacts (base : UInt32) (offset total : Nat)
    (hroom : base.toNat + total ≤ UInt32.size)
    (hoffset : offset + 4 ≤ total) :
    (base + UInt32.ofNat offset).toNat = base.toNat + offset ∧
    ((base + UInt32.ofNat offset) + 1).toNat =
      (base + UInt32.ofNat offset).toNat + 1 ∧
    ((base + UInt32.ofNat offset) + 2).toNat =
      (base + UInt32.ofNat offset).toNat + 2 ∧
    ((base + UInt32.ofNat offset) + 3).toNat =
      (base + UInt32.ofNat offset).toNat + 3 := by
  have hoff : offset < UInt32.size := by
    simp only [UInt32.size] at hroom ⊢
    omega
  have hbaseOffset : base.toNat + offset < UInt32.size := by
    simp only [UInt32.size] at hroom ⊢
    omega
  have h0 := UInt32.add_ofNat_toNat_noWrap base offset hoff hbaseOffset
  have hstep (n : Nat) (hn : n ≤ 3) :
      ((base + UInt32.ofNat offset) + UInt32.ofNat n).toNat =
        (base + UInt32.ofNat offset).toNat + n := by
    apply UInt32.add_ofNat_toNat_noWrap
    · omega
    · rw [h0]
      simp only [UInt32.size] at hroom ⊢
      omega
  exact ⟨h0, by simpa using hstep 1 (by omega),
    by simpa using hstep 2 (by omega), by simpa using hstep 3 (by omega)⟩

private def parseByteParams
    (resultPtr byte radix : UInt32) : List Value :=
  [.i32 resultPtr, .i32 byte, .i32 radix]

private def parseByteLocals
    (frame errorData errorLength tag : UInt32) : List Value :=
  [.i32 frame, .i32 errorData, .i32 errorLength, .i32 tag]

/-- Exact total body contract for the successful numeric-byte path of
generated `func52`. -/
theorem parseByte_body_twp
    [WasmSmallStepGS hlc]
    {s : Stuckness} {E : CoPset}
    {Φ : List Value → IProp WasmHeapGF}
    (resultPtr byte radix stackTop : UInt32)
    (oldFrame4 oldFrame8 oldFrame12 oldResult0 oldResult4 : UInt32)
    (hradixMin : 2 ≤ radix) (hradixMax : radix ≤ 36)
    (hbyteNumeric : byte ≤ 57)
    (hdigit : byte - 48 < radix)
    (hframeRoom : (stackTop - 16).toNat + 16 ≤ UInt32.size)
    (hresultRoom : resultPtr.toNat + 8 ≤ UInt32.size)
    {calls : List CallFrame} :
    globalPointsTo 0 (.i32 stackTop) ∗
      pointsTo_u32 ((stackTop - 16) + 4) oldFrame4 ∗
      pointsTo_u32 ((stackTop - 16) + 8) oldFrame8 ∗
      pointsTo_u32 ((stackTop - 16) + 12) oldFrame12 ∗
      pointsTo_u32 resultPtr oldResult0 ∗
      pointsTo_u32 (resultPtr + 4) oldResult4 ∗
      ((globalPointsTo 0 (.i32 stackTop) ∗
        pointsTo_u32 ((stackTop - 16) + 4) 1 ∗
        pointsTo_u32 ((stackTop - 16) + 8) (byte - 48) ∗
        pointsTo_u32 ((stackTop - 16) + 12) (byte - 48) ∗
        pointsTo_u32 resultPtr 1 ∗
        pointsTo_u32 (resultPtr + 4) (byte - 48)) -∗
        ∀ controls : List ControlFrame,
          WP (.running
            ⟨⟨parseByteParams resultPtr byte radix,
                parseByteLocals (stackTop - 16) 0 0 1, []⟩,
              [.ret], 0, [], controls, calls⟩ : Expr α) @ s; E [{ Φ }]) ⊢
    WP (.running
      ⟨⟨parseByteParams resultPtr byte radix,
          parseByteLocals 0 0 0 0, []⟩,
        func52, 0, [], [], calls⟩ : Expr α) @ s; E [{ Φ }] := by
  let frame := stackTop - 16
  obtain ⟨hf40, hf41, hf42, hf43⟩ :=
    slotFacts frame 4 16 hframeRoom (by decide)
  obtain ⟨hf80, hf81, hf82, hf83⟩ :=
    slotFacts frame 8 16 hframeRoom (by decide)
  obtain ⟨hf120, hf121, hf122, hf123⟩ :=
    slotFacts frame 12 16 hframeRoom (by decide)
  obtain ⟨hr0, hr1, hr2, hr3⟩ :=
    slotFacts resultPtr 0 8 hresultRoom (by decide)
  obtain ⟨hr40, hr41, hr42, hr43⟩ :=
    slotFacts resultPtr 4 8 hresultRoom (by decide)
  have hnotByte : ¬byte > 57 := not_lt_of_ge hbyteNumeric
  iintro ⟨Hglobal, Hf4, Hf8, Hf12, Hr0, Hr4, Hcont⟩
  simp only [func52]
  iapply twp_globalGet0
  isplitl [Hglobal]
  · iexact Hglobal
  iintro Hglobal
  iapply twp_const
  iapply twp_sub
  iapply twp_localSet rfl
  simp only [parseByteParams, parseByteLocals]
  iapply twp_localGet rfl
  iapply twp_globalSet0
  isplitl [Hglobal]
  · iexact Hglobal
  iintro Hglobal
  iapply twp_block
  iapply twp_localGet rfl
  iapply twp_const
  iapply twp_geU (result := 1) (by simp [hradixMin])
  iapply twp_const
  iapply twp_and
  rw [show (1 : UInt32) &&& 1 = 1 by decide]
  iapply twp_eqz (value := 1) (result := 0) (by simp)
  iapply twp_brIfZero
  iapply twp_localGet rfl
  iapply twp_const
  iapply twp_leU (result := 1) (by simp [hradixMax])
  iapply twp_const
  iapply twp_and
  rw [show (1 : UInt32) &&& 1 = 1 by decide]
  iapply twp_eqz (value := 1) (result := 0) (by simp)
  iapply twp_brIfZero
  iapply twp_block
  iapply twp_block
  iapply twp_localGet rfl
  iapply twp_const
  iapply twp_gtU (result := 0) (by simp [hnotByte])
  iapply twp_const
  iapply twp_and
  rw [show (0 : UInt32) &&& 1 = 0 by decide]
  iapply twp_eqz (value := 0) (result := 1) (by simp)
  iapply twp_brIf (by decide) rfl
  simp only [List.drop_zero, List.take_zero, List.nil_append]
  iapply twp_localGet rfl
  iapply twp_localGet rfl
  iapply twp_const
  iapply twp_sub
  iapply twp_store32 oldFrame12 hf120 hf121 hf122 hf123 $$ Hf12
  iintro Hf12
  iapply twp_exitControl rfl
  simp only [List.take_zero, List.nil_append]
  iapply twp_block
  iapply twp_block
  iapply twp_localGet rfl
  iapply twp_load32 (byte - 48) hf120 hf121 hf122 hf123 $$ Hf12
  iintro Hf12
  iapply twp_localGet rfl
  iapply twp_ltU (result := 1) (by simp [hdigit])
  iapply twp_const
  iapply twp_and
  rw [show (1 : UInt32) &&& 1 = 1 by decide]
  iapply twp_brIf (by decide) rfl
  simp only [List.drop_zero, List.take_zero, List.nil_append]
  iapply twp_localGet rfl
  iapply twp_localGet rfl
  iapply twp_load32 (byte - 48) hf120 hf121 hf122 hf123 $$ Hf12
  iintro Hf12
  iapply twp_store32 oldFrame8 hf80 hf81 hf82 hf83 $$ Hf8
  iintro Hf8
  iapply twp_localGet rfl
  iapply twp_const
  iapply twp_store32 oldFrame4 hf40 hf41 hf42 hf43 $$ Hf4
  iintro Hf4
  iapply twp_exitControl rfl
  simp only [List.take_zero, List.nil_append]
  iapply twp_localGet rfl
  iapply twp_load32 1 hf40 hf41 hf42 hf43 $$ Hf4
  iintro Hf4
  iapply twp_localSet rfl
  iapply twp_localGet rfl
  iapply twp_localGet rfl
  iapply twp_load32 (byte - 48) hf80 hf81 hf82 hf83 $$ Hf8
  iintro Hf8
  iapply twp_store32 oldResult4 hr40 hr41 hr42 hr43 $$ Hr4
  iintro Hr4
  iapply twp_localGet rfl
  iapply twp_localGet rfl
  ihave Hr0' : pointsTo_u32 (resultPtr + 0) oldResult0 $$ [Hr0]
  · rw [UInt32.add_zero]
    iexact Hr0
  iapply twp_store32 oldResult0 hr0 hr1 hr2 hr3 $$ Hr0'
  iintro Hr0
  iapply twp_localGet rfl
  iapply twp_const
  iapply twp_add
  iapply twp_globalSet0
  isplitl [Hglobal]
  · iexact Hglobal
  iintro Hglobal
  simp only [List.set, frame,
    List.length_cons, List.length_nil, Nat.reduceAdd, Nat.reduceSub]
  ihave HglobalTop : globalPointsTo 0 (.i32 stackTop) $$ [Hglobal]
  · rw [show (16 : UInt32) + (stackTop - 16) = stackTop by bv_decide]
    iexact Hglobal
  ihave Hr0Plain : pointsTo_u32 resultPtr 1 $$ [Hr0]
  · iapply Project.Mergesort.RangeProof.pointsTo_u32_add_zero
    iexact Hr0
  ispecialize Hcont $$ [HglobalTop Hf4 Hf8 Hf12 Hr0Plain Hr4]
  · iframe
  ispecialize Hcont $$ %_
  iapply Hcont

/-- Composable total call rule for generated `func52` at absolute index `54`.
This is the byte/digit leaf consumed by the loops in `func51`. -/
theorem parseByte_call_twp
    [WasmSmallStepGS hlc]
    {s : Stuckness} {E : CoPset}
    {Φ : List Value → IProp WasmHeapGF}
    (resultPtr byte radix stackTop : UInt32)
    (oldFrame4 oldFrame8 oldFrame12 oldResult0 oldResult4 : UInt32)
    (hradixMin : 2 ≤ radix) (hradixMax : radix ≤ 36)
    (hbyteNumeric : byte ≤ 57)
    (hdigit : byte - 48 < radix)
    (hframeRoom : (stackTop - 16).toNat + 16 ≤ UInt32.size)
    (hresultRoom : resultPtr.toNat + 8 ≤ UInt32.size)
    {callerLocals : Locals} {stack : List Value}
    {code : Program} {arity : Nat} {remainder : List Value}
    {controls : List ControlFrame} {calls : List CallFrame} :
    runtimeModuleOwn «module» ∗
      globalPointsTo 0 (.i32 stackTop) ∗
      pointsTo_u32 ((stackTop - 16) + 4) oldFrame4 ∗
      pointsTo_u32 ((stackTop - 16) + 8) oldFrame8 ∗
      pointsTo_u32 ((stackTop - 16) + 12) oldFrame12 ∗
      pointsTo_u32 resultPtr oldResult0 ∗
      pointsTo_u32 (resultPtr + 4) oldResult4 ∗
      ((runtimeModuleOwn «module» ∗
        globalPointsTo 0 (.i32 stackTop) ∗
        pointsTo_u32 ((stackTop - 16) + 4) 1 ∗
        pointsTo_u32 ((stackTop - 16) + 8) (byte - 48) ∗
        pointsTo_u32 ((stackTop - 16) + 12) (byte - 48) ∗
        pointsTo_u32 resultPtr 1 ∗
        pointsTo_u32 (resultPtr + 4) (byte - 48)) -∗
        WP (.running
          ⟨{ callerLocals with values := stack }, code,
            arity, remainder, controls, calls⟩ : Expr α)
          @ s; E [{ Φ }]) ⊢
    WP (.running
      ⟨{ callerLocals with values :=
          [.i32 radix, .i32 byte, .i32 resultPtr] ++ stack },
        .call 54 :: code, arity, remainder, controls, calls⟩ : Expr α)
      @ s; E [{ Φ }] := by
  iintro ⟨Hruntime, Hglobal, Hf4, Hf8, Hf12, Hr0, Hr4, Hdone⟩
  iapply Wasm.SmallStep.twp_call (α := α) «module» 54 parseByteFunction
      (by decide) parseByte_index $$ Hruntime
  iintro Hruntime
  simp [parseByteFunction, func52Def, Function.toLocals, Function.numParams,
    ValueType.zero]
  have Hbody := parseByte_body_twp (α := α)
    resultPtr byte radix stackTop
    oldFrame4 oldFrame8 oldFrame12 oldResult0 oldResult4
    hradixMin hradixMax hbyteNumeric hdigit hframeRoom hresultRoom
    (s := s) (E := E) (Φ := Φ)
    (calls :=
      { locals := { callerLocals with values := stack }
        continuation := code
        resultArity := arity
        callerRemainder := remainder
        control := controls } :: calls)
  simp only [parseByteParams, parseByteLocals] at Hbody
  iapply Hbody
  isplitl [Hglobal]
  · iexact Hglobal
  isplitl [Hf4]
  · iexact Hf4
  isplitl [Hf8]
  · iexact Hf8
  isplitl [Hf12]
  · iexact Hf12
  isplitl [Hr0]
  · iexact Hr0
  isplitl [Hr4]
  · iexact Hr4
  iintro Hpost
  iintro %calleeControls
  iapply Wasm.SmallStep.twp_returnFromCallExplicit (α := α)
  simp only [List.take_zero, List.nil_append,
    List.drop_eq_nil_of_le (by decide : 3 ≤
      [.i32 resultPtr, .i32 byte, .i32 radix].length)]
  iapply Hdone
  isplitl [Hruntime]
  · iexact Hruntime
  iexact Hpost

end Project.Mergesort.ParseByteProof
