/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.Mergesort

open Wasm

def func0 : Wasm.Program :=
  [
  .globalGet 0,
  .const (32 : UInt32),
  .sub,
  .localSet 3,
  .localGet 3,
  .const (1 : UInt32),
  .store32 (0 : UInt32),
  .loop 0 0 [
    .block 0 0 [
      .localGet 3,
      .load32 (0 : UInt32),
      .localGet 1,
      .ltU,
      .const (1 : UInt32),
      .and,
      .br_if 0,
      .ret
    ],
    .localGet 3,
    .const (0 : UInt32),
    .store32 (4 : UInt32),
    .loop 0 0 [
      .block 0 0 [
        .block 0 0 [
          .block 0 0 [
            .block 0 0 [
              .block 0 0 [
                .localGet 3,
                .load32 (4 : UInt32),
                .localGet 1,
                .ltU,
                .const (1 : UInt32),
                .and,
                .br_if 0,
                .localGet 3,
                .const (0 : UInt32),
                .store32 (28 : UInt32),
                .br 1
              ],
              .localGet 3,
              .load32 (4 : UInt32),
              .localGet 3,
              .load32 (0 : UInt32),
              .add,
              .localGet 1,
              .ltU,
              .const (1 : UInt32),
              .and,
              .br_if 2,
              .br 1
            ],
            .loop 0 0 [
              .block 0 0 [
                .localGet 3,
                .load32 (28 : UInt32),
                .localGet 1,
                .ltU,
                .const (1 : UInt32),
                .and,
                .br_if 0,
                .localGet 3,
                .localGet 3,
                .load32 (0 : UInt32),
                .const (1 : UInt32),
                .shl,
                .store32 (0 : UInt32),
                .br 6
              ],
              .localGet 2,
              .localGet 3,
              .load32 (28 : UInt32),
              .const (3 : UInt32),
              .shl,
              .add,
              .load64 (0 : UInt32),
              .localSet 4,
              .localGet 0,
              .localGet 3,
              .load32 (28 : UInt32),
              .const (3 : UInt32),
              .shl,
              .add,
              .localGet 4,
              .store64 (0 : UInt32),
              .localGet 3,
              .localGet 3,
              .load32 (28 : UInt32),
              .const (1 : UInt32),
              .add,
              .store32 (28 : UInt32),
              .br 0
            ]
          ],
          .localGet 3,
          .localGet 1,
          .store32 (8 : UInt32),
          .br 1
        ],
        .localGet 3,
        .localGet 3,
        .load32 (4 : UInt32),
        .localGet 3,
        .load32 (0 : UInt32),
        .add,
        .store32 (8 : UInt32)
      ],
      .block 0 0 [
        .block 0 0 [
          .localGet 3,
          .load32 (4 : UInt32),
          .localGet 3,
          .load32 (0 : UInt32),
          .const (1 : UInt32),
          .shl,
          .add,
          .localGet 1,
          .ltU,
          .const (1 : UInt32),
          .and,
          .br_if 0,
          .localGet 3,
          .localGet 1,
          .store32 (12 : UInt32),
          .br 1
        ],
        .localGet 3,
        .localGet 3,
        .load32 (4 : UInt32),
        .localGet 3,
        .load32 (0 : UInt32),
        .const (1 : UInt32),
        .shl,
        .add,
        .store32 (12 : UInt32)
      ],
      .localGet 3,
      .localGet 3,
      .load32 (4 : UInt32),
      .store32 (16 : UInt32),
      .localGet 3,
      .localGet 3,
      .load32 (8 : UInt32),
      .store32 (20 : UInt32),
      .localGet 3,
      .localGet 3,
      .load32 (4 : UInt32),
      .store32 (24 : UInt32),
      .block 0 0 [
        .loop 0 0 [
          .localGet 3,
          .load32 (16 : UInt32),
          .localGet 3,
          .load32 (8 : UInt32),
          .ltU,
          .const (1 : UInt32),
          .and,
          .eqz,
          .br_if 1,
          .localGet 3,
          .load32 (20 : UInt32),
          .localGet 3,
          .load32 (12 : UInt32),
          .ltU,
          .const (1 : UInt32),
          .and,
          .eqz,
          .br_if 1,
          .localGet 0,
          .localGet 3,
          .load32 (16 : UInt32),
          .const (3 : UInt32),
          .shl,
          .add,
          .load64 (0 : UInt32),
          .localSet 5,
          .localGet 0,
          .localGet 3,
          .load32 (20 : UInt32),
          .const (3 : UInt32),
          .shl,
          .add,
          .load64 (0 : UInt32),
          .localSet 6,
          .block 0 0 [
            .block 0 0 [
              .localGet 5,
              .localGet 6,
              .leUI64,
              .const (1 : UInt32),
              .and,
              .br_if 0,
              .localGet 2,
              .localGet 3,
              .load32 (24 : UInt32),
              .const (3 : UInt32),
              .shl,
              .add,
              .localGet 6,
              .store64 (0 : UInt32),
              .localGet 3,
              .localGet 3,
              .load32 (20 : UInt32),
              .const (1 : UInt32),
              .add,
              .store32 (20 : UInt32),
              .br 1
            ],
            .localGet 2,
            .localGet 3,
            .load32 (24 : UInt32),
            .const (3 : UInt32),
            .shl,
            .add,
            .localGet 5,
            .store64 (0 : UInt32),
            .localGet 3,
            .localGet 3,
            .load32 (16 : UInt32),
            .const (1 : UInt32),
            .add,
            .store32 (16 : UInt32)
          ],
          .localGet 3,
          .localGet 3,
          .load32 (24 : UInt32),
          .const (1 : UInt32),
          .add,
          .store32 (24 : UInt32),
          .br 0
        ]
      ],
      .loop 0 0 [
        .block 0 0 [
          .localGet 3,
          .load32 (16 : UInt32),
          .localGet 3,
          .load32 (8 : UInt32),
          .ltU,
          .const (1 : UInt32),
          .and,
          .br_if 0,
          .loop 0 0 [
            .block 0 0 [
              .localGet 3,
              .load32 (20 : UInt32),
              .localGet 3,
              .load32 (12 : UInt32),
              .ltU,
              .const (1 : UInt32),
              .and,
              .br_if 0,
              .localGet 3,
              .localGet 3,
              .load32 (0 : UInt32),
              .const (1 : UInt32),
              .shl,
              .localGet 3,
              .load32 (4 : UInt32),
              .add,
              .store32 (4 : UInt32),
              .br 4
            ],
            .localGet 0,
            .localGet 3,
            .load32 (20 : UInt32),
            .const (3 : UInt32),
            .shl,
            .add,
            .load64 (0 : UInt32),
            .localSet 7,
            .localGet 2,
            .localGet 3,
            .load32 (24 : UInt32),
            .const (3 : UInt32),
            .shl,
            .add,
            .localGet 7,
            .store64 (0 : UInt32),
            .localGet 3,
            .localGet 3,
            .load32 (20 : UInt32),
            .const (1 : UInt32),
            .add,
            .store32 (20 : UInt32),
            .localGet 3,
            .localGet 3,
            .load32 (24 : UInt32),
            .const (1 : UInt32),
            .add,
            .store32 (24 : UInt32),
            .br 0
          ]
        ],
        .localGet 0,
        .localGet 3,
        .load32 (16 : UInt32),
        .const (3 : UInt32),
        .shl,
        .add,
        .load64 (0 : UInt32),
        .localSet 8,
        .localGet 2,
        .localGet 3,
        .load32 (24 : UInt32),
        .const (3 : UInt32),
        .shl,
        .add,
        .localGet 8,
        .store64 (0 : UInt32),
        .localGet 3,
        .localGet 3,
        .load32 (16 : UInt32),
        .const (1 : UInt32),
        .add,
        .store32 (16 : UInt32),
        .localGet 3,
        .localGet 3,
        .load32 (24 : UInt32),
        .const (1 : UInt32),
        .add,
        .store32 (24 : UInt32),
        .br 0
      ]
    ]
  ]
]

def func0Def : Wasm.Function :=
  { params := [.i32, .i32, .i32], locals := [.i32, .i64, .i64, .i64, .i64, .i64], body := func0, results := [] }

/-- export: mergesort -/
def func1 : Wasm.Program :=
  [
  .localGet 0,
  .localGet 1,
  .localGet 2,
  .call 0,
  .ret
]

def func1Def : Wasm.Function :=
  { params := [.i32, .i32, .i32], locals := [], body := func1, results := [] }

def «module» : Wasm.Module :=
{
  imports := [],
  funcs := [
    func0Def,
    func1Def
  ],
  exports := [
    { name := "mergesort", funcIdx := 1 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1048576 : UInt32) }
  ],
  types := [
    { params := [.i32, .i32, .i32], results := [] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.Mergesort
