/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.Mergesort

open Wasm

def func0 : Wasm.Program :=
  [
  .block 0 0 [
    .block 0 0 [
      .localGet 4,
      .localGet 2,
      .ltU,
      .const (1 : UInt32),
      .and,
      .eqz,
      .br_if 0,
      .localGet 5,
      .localGet 1,
      .ltU,
      .const (1 : UInt32),
      .and,
      .eqz,
      .br_if 0,
      .localGet 0,
      .localGet 4,
      .const (3 : UInt32),
      .shl,
      .add,
      .load64 (0 : UInt32),
      .localSet 7,
      .localGet 0,
      .localGet 5,
      .const (3 : UInt32),
      .shl,
      .add,
      .load64 (0 : UInt32),
      .localSet 8,
      .block 0 0 [
        .localGet 7,
        .localGet 8,
        .leUI64,
        .const (1 : UInt32),
        .and,
        .br_if 0,
        .localGet 3,
        .localGet 6,
        .const (3 : UInt32),
        .shl,
        .add,
        .localGet 8,
        .store64 (0 : UInt32),
        .localGet 0,
        .localGet 1,
        .localGet 2,
        .localGet 3,
        .localGet 4,
        .localGet 5,
        .const (1 : UInt32),
        .add,
        .localGet 6,
        .const (1 : UInt32),
        .add,
        .call 2,
        .br 2
      ],
      .localGet 3,
      .localGet 6,
      .const (3 : UInt32),
      .shl,
      .add,
      .localGet 7,
      .store64 (0 : UInt32),
      .localGet 0,
      .localGet 1,
      .localGet 2,
      .localGet 3,
      .localGet 4,
      .const (1 : UInt32),
      .add,
      .localGet 5,
      .localGet 6,
      .const (1 : UInt32),
      .add,
      .call 2,
      .br 1
    ],
    .block 0 0 [
      .block 0 0 [
        .localGet 4,
        .localGet 2,
        .ltU,
        .const (1 : UInt32),
        .and,
        .br_if 0,
        .localGet 5,
        .localGet 1,
        .ltU,
        .const (1 : UInt32),
        .and,
        .br_if 1,
        .br 2
      ],
      .localGet 0,
      .localGet 4,
      .const (3 : UInt32),
      .shl,
      .add,
      .load64 (0 : UInt32),
      .localSet 9,
      .localGet 3,
      .localGet 6,
      .const (3 : UInt32),
      .shl,
      .add,
      .localGet 9,
      .store64 (0 : UInt32),
      .localGet 0,
      .localGet 1,
      .localGet 2,
      .localGet 3,
      .localGet 4,
      .const (1 : UInt32),
      .add,
      .localGet 5,
      .localGet 6,
      .const (1 : UInt32),
      .add,
      .call 2,
      .br 1
    ],
    .localGet 0,
    .localGet 5,
    .const (3 : UInt32),
    .shl,
    .add,
    .load64 (0 : UInt32),
    .localSet 10,
    .localGet 3,
    .localGet 6,
    .const (3 : UInt32),
    .shl,
    .add,
    .localGet 10,
    .store64 (0 : UInt32),
    .localGet 0,
    .localGet 1,
    .localGet 2,
    .localGet 3,
    .localGet 4,
    .localGet 5,
    .const (1 : UInt32),
    .add,
    .localGet 6,
    .const (1 : UInt32),
    .add,
    .call 2
  ],
  .ret
]

def func0Def : Wasm.Function :=
  { params := [.i32, .i32, .i32, .i32, .i32, .i32, .i32], locals := [.i64, .i64, .i64, .i64], body := func0, results := [] }

def func1 : Wasm.Program :=
  [
  .block 0 0 [
    .localGet 1,
    .const (1 : UInt32),
    .leU,
    .const (1 : UInt32),
    .and,
    .br_if 0,
    .localGet 1,
    .const (1 : UInt32),
    .shrU,
    .localSet 3,
    .localGet 0,
    .localGet 3,
    .localGet 2,
    .call 3,
    .localGet 0,
    .localGet 3,
    .const (3 : UInt32),
    .shl,
    .add,
    .localGet 1,
    .localGet 3,
    .sub,
    .localGet 2,
    .localGet 3,
    .const (3 : UInt32),
    .shl,
    .add,
    .call 3,
    .localGet 0,
    .localGet 1,
    .localGet 3,
    .localGet 2,
    .call 4
  ],
  .ret
]

def func1Def : Wasm.Function :=
  { params := [.i32, .i32, .i32], locals := [.i32], body := func1, results := [] }

def func2 : Wasm.Program :=
  [
  .const (0 : UInt32),
  .localSet 4,
  .localGet 0,
  .localGet 1,
  .localGet 2,
  .localGet 3,
  .localGet 4,
  .localGet 2,
  .localGet 4,
  .call 2,
  .localGet 0,
  .localGet 3,
  .localGet 1,
  .const (0 : UInt32),
  .call 5,
  .ret
]

def func2Def : Wasm.Function :=
  { params := [.i32, .i32, .i32, .i32], locals := [.i32], body := func2, results := [] }

def func3 : Wasm.Program :=
  [
  .block 0 0 [
    .localGet 3,
    .localGet 2,
    .ltU,
    .const (1 : UInt32),
    .and,
    .eqz,
    .br_if 0,
    .localGet 1,
    .localGet 3,
    .const (3 : UInt32),
    .shl,
    .add,
    .load64 (0 : UInt32),
    .localSet 4,
    .localGet 0,
    .localGet 3,
    .const (3 : UInt32),
    .shl,
    .add,
    .localGet 4,
    .store64 (0 : UInt32),
    .localGet 0,
    .localGet 1,
    .localGet 2,
    .localGet 3,
    .const (1 : UInt32),
    .add,
    .call 5
  ],
  .ret
]

def func3Def : Wasm.Function :=
  { params := [.i32, .i32, .i32, .i32], locals := [.i64], body := func3, results := [] }

def func4 : Wasm.Program :=
  [
  .const (1048576 : UInt32),
  .const (32768 : UInt32),
  .call 7,
  .localSet 0,
  .localGet 0,
  .const (3 : UInt32),
  .shrU,
  .localSet 1,
  .const (1048576 : UInt32),
  .localGet 1,
  .const (3 : UInt32),
  .shl,
  .add,
  .localSet 2,
  .const (1048576 : UInt32),
  .localGet 1,
  .localGet 2,
  .call 3,
  .const (1048576 : UInt32),
  .localGet 0,
  .call 8,
  .ret
]

def func4Def : Wasm.Function :=
  { params := [], locals := [.i32, .i32, .i32], body := func4, results := [] }

def func5 : Wasm.Program :=
  [
  .localGet 0,
  .localGet 1,
  .call 0,
  .ret
]

def func5Def : Wasm.Function :=
  { params := [.i32, .i32], locals := [], body := func5, results := [.i32] }

/-- export: mergesort -/
def func6 : Wasm.Program :=
  [
  .localGet 0,
  .localGet 1,
  .call 1,
  .ret
]

def func6Def : Wasm.Function :=
  { params := [.i32, .i32], locals := [], body := func6, results := [] }

def «module» : Wasm.Module :=
{
  imports := [
    { «module» := "stdio", name := "read", params := [.i32, .i32], results := [.i32] },
    { «module» := "stdio", name := "write", params := [.i32, .i32], results := [] }
  ],
  funcs := [
    func0Def,
    func1Def,
    func2Def,
    func3Def,
    func4Def,
    func5Def,
    func6Def
  ],
  exports := [
    { name := "mergesort", funcIdx := 6 }
  ],
  memory := some { pagesMin := (17 : UInt32), pagesMax := none, data := [] },
  globals := [
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1114112 : UInt32) },
    { init := .i32 (1114112 : UInt32) }
  ],
  types := [
    { params := [.i32, .i32], results := [.i32] },
    { params := [.i32, .i32], results := [] },
    { params := [.i32, .i32, .i32, .i32, .i32, .i32, .i32], results := [] },
    { params := [.i32, .i32, .i32], results := [] },
    { params := [.i32, .i32, .i32, .i32], results := [] },
    { params := [], results := [] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.Mergesort
