import Project.Mergesort.ReallocatorExecution
import Project.Mergesort.Func1Proof
import CodeLib.SepLogic.CostedLoop

/-!
# Operational work of generated byte-vector reserve

The reserve path includes the concrete grow wrapper, allocation or reallocation,
result-slot writes, vector-header replacement, and stack-pointer restoration.
-/

namespace Project.Mergesort.ReserveCost

open Wasm Wasm.SmallStep Project.Mergesort.Representations
open Project.Mergesort.Func0Proof

private def blockAt (program : Program) (i : Nat) : Program :=
  match program[i]? with
  | some (.block _ _ body) => body
  | _ => []

private def outer := func0OuterBody
private def middle := blockAt outer 2
private def choose := blockAt middle 0
private def allocate := blockAt choose 0
private def reallocate := blockAt allocate 0
private def nonzero := blockAt allocate 1

private def frame (body continuation : Program) : ControlFrame :=
  { kind := .block, paramArity := 0, resultArity := 0,
    body, continuation, belowStack := [] }

private def outerFrame := frame outer func0FinalCode
private def middleFrame := frame middle (outer.drop 3)
private def chooseFrame := frame choose (middle.drop 1)
private def allocateFrame := frame allocate (choose.drop 1)
private def reallocateFrame := frame reallocate (allocate.drop 1)

private def growLocals (result oldCapacity oldPtr newCapacity status temp : UInt32)
    (product : UInt64) (values : List Value := []) : Locals :=
  ⟨[.i32 result, .i32 oldCapacity, .i32 oldPtr, .i32 newCapacity, .i32 1, .i32 1],
    [.i32 status, .i32 temp, .i64 product], values⟩

private def callerFrame (store : MachineStore α) (caller : ThreadState α) : CallFrame :=
  { locals := caller.locals, continuation := caller.code, resultArity := caller.resultArity,
    callerRemainder := caller.callerRemainder, control := caller.control,
    returningInstance := store.runtime.entry }

def growCall (store : MachineStore α) (result oldCapacity oldPtr newCapacity : UInt32)
    (caller : ThreadState α) : Config α :=
  ⟨.running { caller with
    locals := { caller.locals with values := [.i32 1, .i32 1, .i32 newCapacity, .i32 oldPtr, .i32 oldCapacity, .i32 result] ++ caller.locals.values }
    code := .call 3 :: caller.code }, store⟩

private def growPrefixTrace : List StepKind :=
  [.call 3, .const 1, .localSet 6, .const 4, .localSet 7,
    .block 0 0 outer, .block 0 0 (blockAt outer 0),
    .localGet 5, .extendUI32, .localGet 3, .extendUI32, .mulI64,
    .localTee 8, .constI64 32, .shrUI64, .wrapI64, .eqz, .br_if 0,
    .block 0 0 (blockAt outer 1), .localGet 8, .wrapI64, .localTee 3,
    .const 2147483648, .localGet 4, .sub, .leU, .br_if 0,
    .block 0 0 middle, .block 0 0 choose, .block 0 0 allocate,
    .block 0 0 reallocate].map StepKind.instruction

private theorem grow_prefix (store : MachineStore α)
    (result oldCapacity oldPtr newCapacity : UInt32) (caller : ThreadState α)
    (hmodule : store.runtime.currentModule = Project.Mergesort.module)
    (hnew : newCapacity.toNat ≤ 2147483647)
    (hostBytes : Config α → Nat → Config α → Nat) :
    ∃ trace, trace.length = 31 ∧ CostedSteps (byteWork hostBytes)
      (growCall store result oldCapacity oldPtr newCapacity caller) trace
      ⟨.running ⟨growLocals result oldCapacity oldPtr newCapacity 1 4 newCapacity.toUInt64,
        reallocate, 0, [],
        [reallocateFrame, allocateFrame, chooseFrame, middleFrame, outerFrame],
        callerFrame store caller :: caller.calls⟩, store⟩ trace.length := by
  have hhigh : UInt64.ofNat newCapacity.toNat >>> (32 : UInt64) = 0 := by
    apply UInt64.toNat.inj
    rw [UInt64.toNat_shiftRight]
    rw [show (32 : UInt64).toNat % 64 = 32 by decide]
    norm_num [Nat.shiftRight_eq_div_pow]
    have hw := newCapacity.toBitVec.isLt
    omega
  have hguard : newCapacity ≤ (2147483648 : UInt32) - 1 := by
    rw [UInt32.le_iff_toNat_le_toNat]
    exact hnew
  refine ⟨growPrefixTrace, rfl, ?_⟩
  apply Steps.with_unit_cost
  · unfold growCall growPrefixTrace
    apply Steps.cons (Step.call (fn := func0Def)
      (by rw [hmodule]; decide) (by rw [hmodule]; rfl))
    simp only [func0Def, func0, Function.toLocals, Function.numParams]
    wasm_steps [.const, (.localSet rfl), .const, (.localSet rfl), .block, .block,
      (.localGet rfl), .extendUI32, (.localGet rfl), .extendUI32, .mulI64]
    simp only [extendUnsigned32To64_eq, UInt32.toNat_one, UInt64.ofNat_one, UInt64.one_mul]
    wasm_steps [(.localTee rfl), .constI64, .shrUI64]
    rw [show (32 : UInt64) % 64 = 32 by decide, hhigh]
    wasm_steps [.wrapI64, (.eqz (result := 1) (by decide)), (.brIf (by decide) rfl),
      .block, (.localGet rfl), .wrapI64]
    rw [wrap64To32_eq]
    simp only [UInt64.ofNat_uInt32ToNat, UInt32.toNat_toUInt64, UInt32.ofNat_mod_size, UInt32.ofNat_toNat]
    wasm_steps [(.localTee rfl), .const, (.localGet rfl), .sub,
      (.leU (result := 1) (by rw [if_pos hguard])), (.brIf (by decide) rfl),
      .block, .block, .block, .block]
    exact Steps.refl _
  · intro before kind after member
    fin_cases member <;> rfl

/-- Exact successful grow-result writeback: pointer, capacity, then tag zero. -/
def growResultStore (store : MachineStore α) (result base newCapacity : UInt32) : MachineStore α :=
  { store with wasm := { store.wasm with mem :=
      ((store.wasm.mem.write32 (result + 4) base).write32 (result + 8) newCapacity).write32 result 0 } }

private def successTrace : List StepKind :=
  [.instruction (.localGet 7), .instruction (.br_if 0),
    .instruction (.localGet 0), .instruction (.localGet 7), .instruction (.store32 4),
    .instruction (.const 0), .instruction (.localSet 6), .administrative .exitControl,
    .instruction (.const 8), .instruction (.localSet 7), .administrative .exitControl] ++
    func0FinalCode.map StepKind.instruction ++ [.administrative .returnFromCall]

private theorem grow_success (store : MachineStore α)
    (result oldCapacity oldPtr newCapacity base : UInt32) (caller : ThreadState α)
    (hbase : base ≠ 0) (hresultWord : result.toNat + 12 < UInt32.size)
    (hresult : result.toNat + 12 ≤ store.wasm.mem.pages * 65536)
    (hostBytes : Config α → Nat → Config α → Nat) :
    CostedSteps (byteWork hostBytes)
      ⟨.running ⟨growLocals result oldCapacity oldPtr newCapacity 1 base newCapacity.toUInt64,
        choose.drop 1, 0, [], [chooseFrame, middleFrame, outerFrame],
        callerFrame store caller :: caller.calls⟩, store⟩ successTrace
      ⟨.running caller, growResultStore store result base newCapacity⟩ 20 := by
  have hresult8 : (result + 8).toNat = result.toNat + 8 := by
    simpa using byteOffset_toNat result 8 (by omega)
  have execution : Steps
      ⟨.running ⟨growLocals result oldCapacity oldPtr newCapacity 1 base newCapacity.toUInt64,
        choose.drop 1, 0, [], [chooseFrame, middleFrame, outerFrame],
        callerFrame store caller :: caller.calls⟩, store⟩ successTrace
      ⟨.running caller, growResultStore store result base newCapacity⟩ := by
    unfold successTrace
    wasm_steps [(.localGet rfl), (.brIf hbase rfl), (.localGet rfl), (.localGet rfl)]
    apply Steps.cons (Step.store32 (logicalAddress := result.toNat) (physicalAddress := result)
      rfl (by change result.toNat + 4 + 4 ≤ store.wasm.mem.pages * 65536; omega))
    simp only [setMemory_eq]
    wasm_steps [.const, (.localSet rfl), (.exitControl rfl), .const, (.localSet rfl),
      (.exitControl rfl), (.localGet rfl), (.localGet rfl), .add]
    rw [UInt32.add_comm (8 : UInt32) result]
    wasm_steps [(.localGet rfl)]
    apply Steps.cons (Step.store32 (logicalAddress := (result + 8).toNat) (physicalAddress := result + 8)
      rfl (by change (result + 8).toNat + 0 + 4 ≤ store.wasm.mem.pages * 65536; rw [hresult8]; omega))
    simp only [setMemory_eq, UInt32.add_zero]
    wasm_steps [(.localGet rfl), (.localGet rfl)]
    apply Steps.cons (Step.store32 (logicalAddress := result.toNat) (physicalAddress := result)
      rfl (by change result.toNat + 0 + 4 ≤ store.wasm.mem.pages * 65536; omega))
    simp only [setMemory_eq, UInt32.add_zero]
    exact Steps.single (Step.returnFromCallFallthrough rfl)
  exact execution.with_unit_cost (by
    intro before kind after member
    fin_cases member <;> rfl)

private def allocationCaller (store : MachineStore α)
    (result oldPtr newCapacity : UInt32) (caller : ThreadState α) : ThreadState α :=
  ⟨growLocals result 0 oldPtr newCapacity 1 4 newCapacity.toUInt64,
    allocate.drop 6, 0, [], [allocateFrame, chooseFrame, middleFrame, outerFrame],
    callerFrame store caller :: caller.calls⟩

private def reallocationCaller (store : MachineStore α)
    (result oldCapacity oldPtr newCapacity : UInt32) (caller : ThreadState α) : ThreadState α :=
  ⟨growLocals result oldCapacity oldPtr newCapacity 1 4 newCapacity.toUInt64,
    reallocate.drop 10, 0, [],
    [reallocateFrame, allocateFrame, chooseFrame, middleFrame, outerFrame],
    callerFrame store caller :: caller.calls⟩

private theorem reallocation_prefix (store : MachineStore α)
    (result oldCapacity oldPtr newCapacity : UInt32) (caller : ThreadState α)
    (hold : oldCapacity ≠ 0) (hostBytes : Config α → Nat → Config α → Nat) :
    CostedSteps (byteWork hostBytes)
      ⟨.running ⟨growLocals result oldCapacity oldPtr newCapacity 1 4 newCapacity.toUInt64,
        reallocate, 0, [],
        [reallocateFrame, allocateFrame, chooseFrame, middleFrame, outerFrame],
        callerFrame store caller :: caller.calls⟩, store⟩
      ((reallocate.take 9).map StepKind.instruction)
      ⟨.running { reallocationCaller store result oldCapacity oldPtr newCapacity caller with
        locals := growLocals result oldCapacity oldPtr newCapacity 1 4 newCapacity.toUInt64
          [.i32 newCapacity, .i32 1, .i32 oldCapacity, .i32 oldPtr]
        code := .call 11 :: reallocate.drop 10 }, store⟩ 9 := by
  apply Steps.with_unit_cost
  · wasm_steps [(.localGet rfl), (.eqz (result := 0) (by simp [hold])), .brIfZero,
      (.localGet rfl), (.localGet rfl), (.localGet rfl), .mul]
    simp only [UInt32.mul_one]
    wasm_steps [(.localGet rfl), (.localGet rfl)]
    exact Steps.refl _
  · intro before kind after member
    fin_cases member <;> rfl

private def firstAllocationTrace : List StepKind :=
  [.instruction (.localGet 1), .instruction .eqz, .instruction (.br_if 0),
    .instruction (.block 0 0 nonzero), .instruction (.localGet 3), .instruction (.br_if 0),
    .instruction (.call 7), .administrative .returnFromCall,
    .instruction (.localGet 3), .instruction (.localGet 4)]

private theorem allocation_prefix (store : MachineStore α)
    (result oldPtr newCapacity : UInt32) (caller : ThreadState α)
    (hmodule : store.runtime.currentModule = Project.Mergesort.module)
    (hnew : newCapacity ≠ 0) (hostBytes : Config α → Nat → Config α → Nat) :
    CostedSteps (byteWork hostBytes)
      ⟨.running ⟨growLocals result 0 oldPtr newCapacity 1 4 newCapacity.toUInt64,
        reallocate, 0, [],
        [reallocateFrame, allocateFrame, chooseFrame, middleFrame, outerFrame],
        callerFrame store caller :: caller.calls⟩, store⟩ firstAllocationTrace
      ⟨.running { allocationCaller store result oldPtr newCapacity caller with
        locals := growLocals result 0 oldPtr newCapacity 1 4 newCapacity.toUInt64
          [.i32 1, .i32 newCapacity]
        code := .call 8 :: allocate.drop 6 }, store⟩ 10 := by
  apply Steps.with_unit_cost
  · unfold firstAllocationTrace
    wasm_steps [(.localGet rfl), (.eqz (result := 1) rfl), (.brIf (by decide) rfl),
      .block, (.localGet rfl), (.brIf hnew rfl)]
    apply Steps.cons (Step.call (fn := func4Def)
      (by rw [hmodule]; decide) (by rw [hmodule]; rfl))
    wasm_steps [(.returnFromCallExplicit rfl), (.localGet rfl), (.localGet rfl)]
    exact Steps.refl _
  · intro before kind after member
    fin_cases member <;> rfl

private theorem allocation_join (store : MachineStore α)
    (result oldPtr newCapacity base : UInt32) (caller : ThreadState α)
    (hostBytes : Config α → Nat → Config α → Nat) :
    CostedSteps (byteWork hostBytes)
      ⟨.running { allocationCaller store result oldPtr newCapacity caller with
        locals := growLocals result 0 oldPtr newCapacity 1 4 newCapacity.toUInt64 [.i32 base] }, store⟩
      [.instruction (.localSet 7), .administrative .exitControl]
      ⟨.running ⟨growLocals result 0 oldPtr newCapacity 1 base newCapacity.toUInt64,
        choose.drop 1, 0, [], [chooseFrame, middleFrame, outerFrame],
        callerFrame store caller :: caller.calls⟩, store⟩ 2 := by
  apply Steps.with_unit_cost
  · exact .cons (.localSet rfl) (.single (.exitControl rfl))
  · intro before kind after member
    fin_cases member <;> rfl

private theorem reallocation_join (store : MachineStore α)
    (result oldCapacity oldPtr newCapacity base : UInt32) (caller : ThreadState α)
    (hostBytes : Config α → Nat → Config α → Nat) :
    CostedSteps (byteWork hostBytes)
      ⟨.running { reallocationCaller store result oldCapacity oldPtr newCapacity caller with
        locals := growLocals result oldCapacity oldPtr newCapacity 1 4 newCapacity.toUInt64 [.i32 base] }, store⟩
      [.instruction (.localSet 7), .instruction (.br 1)]
      ⟨.running ⟨growLocals result oldCapacity oldPtr newCapacity 1 base newCapacity.toUInt64,
        choose.drop 1, 0, [], [chooseFrame, middleFrame, outerFrame],
        callerFrame store caller :: caller.calls⟩, store⟩ 2 := by
  apply Steps.with_unit_cost
  · exact .cons (.localSet rfl) (.single (.br rfl))
  · intro before kind after member
    fin_cases member <;> rfl

/-- Actual allocation branch selected by the old capacity. -/
def allocationStore (store : MachineStore α) (oldCapacity oldPtr base finish : UInt32) : MachineStore α :=
  if oldCapacity = 0 then AllocatorExecution.finalStore store finish
  else ReallocatorExecution.finalStore store oldPtr oldCapacity base finish

/-- The concrete memory after the complete grow wrapper. -/
def growFinalStore (store : MachineStore α)
    (result oldCapacity oldPtr newCapacity base finish : UInt32) : MachineStore α :=
  growResultStore (allocationStore store oldCapacity oldPtr base finish) result base newCapacity

/-- Complete generated grow call 3, including either allocation branch,
physical copying/growth, result writes and caller return. -/
theorem grow_call_byteWork (store : MachineStore α)
    (result oldCapacity oldPtr newCapacity : UInt32) (frontier : Nat)
    (storedCursor base finish : UInt32) (caller : ThreadState α)
    (hmodule : store.runtime.currentModule = Project.Mergesort.module)
    (hcap : store.wasm.memoryCap store.runtime.currentModule 0 = Module.memoryHardCap)
    (hpages : store.wasm.mem.pages ≤ Module.memoryHardCap)
    (hfrontier : heapBase.toNat ≤ frontier)
    (hvalid : ({ size := newCapacity.toNat, alignment := 1 } : AllocLayout).Valid)
    (hclassify : classifyBump frontier { size := newCapacity.toNat, alignment := 1 } = .success base finish)
    (hcursor : store.wasm.mem.read32 allocatorCursor = storedCursor)
    (heffective : (if storedCursor ≠ 0 then storedCursor else heapBase) = UInt32.ofNat frontier)
    (hcursorBounds : allocatorCursor.toNat + 4 ≤ store.wasm.mem.pages * 65536)
    (hold : oldCapacity.toNat < newCapacity.toNat)
    (hsource : oldPtr.toNat + oldCapacity.toNat ≤ store.wasm.mem.pages * 65536)
    (hresultWord : result.toNat + 12 < UInt32.size)
    (hresult : result.toNat + 12 ≤ store.wasm.mem.pages * 65536)
    (hostBytes : Config α → Nat → Config α → Nat) :
    ∃ trace, trace.length ≤ (if oldCapacity = 0 then 119 else 137) ∧
      CostedSteps (byteWork hostBytes) (growCall store result oldCapacity oldPtr newCapacity caller)
        trace ⟨.running caller, growFinalStore store result oldCapacity oldPtr newCapacity base finish⟩
        (trace.length + oldCapacity.toNat + 65536 *
          ((allocatorRequiredPages finish).toNat - store.wasm.mem.pages)) := by
  let layout : AllocLayout := { size := newCapacity.toNat, alignment := 1 }
  have hnew : newCapacity.toNat ≤ 2147483647 := hvalid.2.2.2.2.1
  have hnewNonzero : newCapacity ≠ 0 := by
    intro hz
    rw [hz] at hold
    exact Nat.not_lt_zero _ hold
  have hbase := (classifyBump_success_reachable frontier layout base finish
    hfrontier hvalid (Or.inl rfl) hclassify).2.1
  obtain ⟨startTrace, hprefixLength, hprefix⟩ :=
    grow_prefix store result oldCapacity oldPtr newCapacity caller hmodule hnew hostBytes
  by_cases hzero : oldCapacity = 0
  · subst oldCapacity
    let ac := allocationCaller store result oldPtr newCapacity caller
    have first := allocation_prefix store result oldPtr newCapacity caller hmodule hnewNonzero hostBytes
    obtain ⟨allocationTrace, allocationBound, allocationRun⟩ :=
      AllocatorExecution.func5_call_byteWork store layout frontier storedCursor base finish
        ac.locals [] ac.code ac.resultArity ac.callerRemainder ac.control ac.calls
        hmodule hcap hpages (Or.inl rfl) hclassify hcursor heffective hcursorBounds hostBytes
    simp only [layout, UInt32.ofNat_toNat] at allocationRun
    let allocated := AllocatorExecution.finalStore store finish
    have joined := allocation_join allocated result oldPtr newCapacity base caller hostBytes
    have tail := grow_success allocated result 0 oldPtr newCapacity base caller hbase hresultWord
      (hresult.trans (Nat.mul_le_mul_right 65536 (Nat.le_max_left _ _))) hostBytes
    refine ⟨((startTrace ++ firstAllocationTrace) ++ allocationTrace) ++
      [.instruction (.localSet 7), .administrative .exitControl] ++ successTrace, ?_, ?_⟩
    · simp only [List.length_append, hprefixLength]
      change 31 + 10 + allocationTrace.length + 2 + 20 ≤ 119
      omega
    · have run := (((hprefix.trans first).trans allocationRun).trans joined).trans tail
      convert run using 1 <;>
        simp [growFinalStore, allocationStore, allocated, List.length_append,
          hprefixLength, firstAllocationTrace, successTrace, func0FinalCode, Nat.add_assoc]
      omega
  · let rc := reallocationCaller store result oldCapacity oldPtr newCapacity caller
    have first := reallocation_prefix store result oldCapacity oldPtr newCapacity caller hzero hostBytes
    have hpositive : 0 < oldCapacity.toNat := by
      by_contra hn
      have hz : oldCapacity.toNat = 0 := by omega
      exact hzero (UInt32.toNat.inj hz)
    obtain ⟨allocationTrace, allocationBound, allocationRun, _⟩ :=
      ReallocatorExecution.func8_call_byteWork store layout oldPtr oldCapacity frontier storedCursor base finish
        rc.locals [] rc.code rc.resultArity rc.callerRemainder rc.control rc.calls
        hmodule hcap hpages hfrontier hvalid rfl hclassify hcursor heffective hcursorBounds
        hpositive hold hsource hostBytes
    simp only [layout, UInt32.ofNat_toNat] at allocationRun
    let allocated := ReallocatorExecution.finalStore store oldPtr oldCapacity base finish
    have joined := reallocation_join allocated result oldCapacity oldPtr newCapacity base caller hostBytes
    have tail := grow_success allocated result oldCapacity oldPtr newCapacity base caller hbase hresultWord
      (hresult.trans (Nat.mul_le_mul_right 65536 (Nat.le_max_left _ _))) hostBytes
    refine ⟨((startTrace ++ (reallocate.take 9).map StepKind.instruction) ++ allocationTrace) ++
      [.instruction (.localSet 7), .instruction (.br 1)] ++ successTrace, ?_, ?_⟩
    · simp only [if_neg hzero, List.length_append, hprefixLength]
      change 31 + 9 + allocationTrace.length + 2 + 20 ≤ 137
      omega
    · have run := (((hprefix.trans first).trans allocationRun).trans joined).trans tail
      convert run using 1 <;>
        simp [growFinalStore, allocationStore, hzero, allocated, List.length_append,
          hprefixLength, successTrace, func0FinalCode, reallocate, allocate, choose, middle, outer,
          blockAt, func0OuterBody, func0, Nat.add_assoc]
      omega

/-- Final memory of canonical reserve, with the caller's stack global restored.
The operational theorem proves that restoration from its initial global fact. -/
def finalStore (store : MachineStore α) (oldCapacity oldPtr newCapacity base finish : UInt32) : MachineStore α :=
  let grown := growFinalStore store (reserveBase + 4) oldCapacity oldPtr newCapacity base finish
  { grown with wasm := { grown.wasm with mem :=
      (grown.wasm.mem.write32 driverBase newCapacity).write32 (driverBase + 4) base } }

private def stackStore (store : MachineStore α) (value : UInt32) : MachineStore α :=
  { store with wasm := { store.wasm with globals := { globals := store.wasm.globals.globals.set 0 (.i32 value) } } }

private def reserveLocals (v1 v2 v4 sp : UInt32) (values : List Value := []) : Locals :=
  ⟨[.i32 driverBase, .i32 v1, .i32 v2, .i32 1, .i32 v4], [.i32 sp], values⟩

def reserveCall (store : MachineStore α) (length additional : UInt32)
    (caller : ThreadState α) : Config α :=
  ⟨.running { caller with
    locals := { caller.locals with values := [.i32 1, .i32 1, .i32 additional, .i32 length, .i32 driverBase] ++ caller.locals.values }
    code := .call 4 :: caller.code }, store⟩

private def reserveGrowCaller (store : MachineStore α) (newCapacity : UInt32)
    (caller : ThreadState α) : ThreadState α :=
  ⟨reserveLocals 8 newCapacity 1 reserveBase, func1.drop 39, 0, [], [],
    callerFrame store caller :: caller.calls⟩

private theorem maxWord (a b : Nat) (ha : a < UInt32.size) (hb : b < UInt32.size) :
    .i32 (UInt32.ofNat (max a b)) =
      (if (if UInt32.ofNat a > UInt32.ofNat b then 1 else 0 : UInt32) ≠ 0
       then (.i32 (UInt32.ofNat a) : Value) else .i32 (UInt32.ofNat b)) := by
  have hcmp : (UInt32.ofNat a > UInt32.ofNat b) ↔ b < a := by
    change UInt32.ofNat b < UInt32.ofNat a ↔ b < a
    rw [UInt32.lt_iff_toNat_lt, UInt32.toNat_ofNat_of_lt' ha, UInt32.toNat_ofNat_of_lt' hb]
  by_cases h : b < a
  · simp [hcmp, h, max_eq_left (Nat.le_of_lt h)]
  · simp [hcmp, h, max_eq_right (by omega : a ≤ b)]

private def reservePrefixTrace : List StepKind :=
  [.instruction (.call 4)] ++ (func1.take 5).map StepKind.instruction ++
    [.instruction (.block 0 0 (blockAt func1 5))] ++
    ((blockAt func1 5).take 7).map StepKind.instruction ++
    ((func1.drop 6).take 32).map StepKind.instruction

private theorem reserve_prefix (store : MachineStore α)
    (length additional capacity ptr : UInt32) (caller : ThreadState α)
    (hmodule : store.runtime.currentModule = Project.Mergesort.module)
    (hglobal : globalAt? store 0 = some (.i32 driverBase))
    (hcapacity : store.wasm.mem.read32 driverBase = capacity)
    (hpointer : store.wasm.mem.read32 (driverBase + 4) = ptr)
    (hheader : driverBase.toNat + 12 ≤ store.wasm.mem.pages * 65536)
    (hnew : selectedCapacity length.toNat additional.toNat capacity.toNat < UInt32.size)
    (hostBytes : Config α → Nat → Config α → Nat) :
    let newCapacity := UInt32.ofNat (selectedCapacity length.toNat additional.toNat capacity.toNat)
    CostedSteps (byteWork hostBytes) (reserveCall store length additional caller) reservePrefixTrace
      (growCall (stackStore store reserveBase) (reserveBase + 4) capacity ptr newCapacity
        (reserveGrowCaller store newCapacity caller)) 46 := by
  intro newCapacity
  let total := length.toNat + additional.toNat
  let doubled := 2 * capacity.toNat
  let firstMax := max total doubled
  have htotal : total < UInt32.size := by dsimp [total]; unfold selectedCapacity at hnew; omega
  have hdouble : doubled < UInt32.size := by dsimp [doubled]; unfold selectedCapacity at hnew; omega
  have hfirst : firstMax < UInt32.size := by dsimp [firstMax]; omega
  have hsumWord : length + additional = UInt32.ofNat total := by
    rw [← UInt32.ofNat_toNat (x := length), ← UInt32.ofNat_toNat (x := additional), ← UInt32.ofNat_add]
  have hguard : additional ≤ UInt32.ofNat total := by
    rw [UInt32.le_iff_toNat_le_toNat, UInt32.toNat_ofNat_of_lt' htotal]
    dsimp [total]; omega
  have hdoubleWord : capacity <<< (1 : UInt32) = UInt32.ofNat doubled := by
    apply UInt32.toNat.inj
    rw [UInt32.toNat_shiftLeft, show (1 : UInt32).toNat % 32 = 1 by decide,
      Nat.shiftLeft_eq, pow_one, UInt32.toNat_ofNat_of_lt' hdouble]
    dsimp [doubled]
    rw [Nat.mod_eq_of_lt (by change capacity.toNat * 2 < UInt32.size; dsimp [doubled] at hdouble; omega)]
    omega
  have hsecond : max firstMax 8 = selectedCapacity length.toNat additional.toNat capacity.toNat := by
    dsimp [firstMax, total, doubled, selectedCapacity]
    omega
  apply Steps.with_unit_cost
  · unfold reserveCall reservePrefixTrace
    apply Steps.cons (Step.call (fn := func1Def)
      (by rw [hmodule]; decide) (by rw [hmodule]; rfl))
    simp only [func1Def, func1, Function.toLocals, Function.numParams]
    wasm_steps [(.globalGet hglobal), .const, .sub]
    rw [show driverBase - 16 = reserveBase by decide]
    wasm_steps [(.localTee rfl), (.globalSet (by rw [hglobal]; rfl))]
    rw [setGlobal_zero_eq]
    wasm_steps [.block, (.localGet rfl), (.localGet rfl), .add]
    rw [hsumWord]
    wasm_steps [(.localTee rfl), (.localGet rfl), (.geU (result := 1) (by rw [if_pos hguard])),
      (.brIf (by decide) rfl), (.localGet rfl), .const, .add]
    rw [UInt32.add_comm 4 reserveBase]
    wasm_steps [(.localGet rfl)]
    apply Steps.cons (Step.load32 (logicalAddress := driverBase.toNat) (physicalAddress := driverBase)
      rfl (by change driverBase.toNat + 0 + 4 ≤ store.wasm.mem.pages * 65536; omega))
    rw [UInt32.add_zero, hcapacity]
    wasm_steps [(.localTee rfl), (.localGet rfl)]
    apply Steps.cons (Step.load32 (logicalAddress := driverBase.toNat) (physicalAddress := driverBase)
      rfl (by change driverBase.toNat + 4 + 4 ≤ store.wasm.mem.pages * 65536; omega))
    rw [hpointer]
    wasm_steps [(.localGet rfl), (.localGet rfl), .const, .shl]
    rw [show (1 : UInt32) % 32 = 1 by decide, hdoubleWord]
    wasm_steps [(.localTee rfl), (.localGet rfl), (.localGet rfl), (.gtU rfl)]
    apply Steps.cons (Step.select (maxWord total doubled htotal hdouble))
    wasm_steps [(.localTee rfl), .const, .const, (.localGet rfl), .const,
      (.eq (result := 1) rfl), (.select (selected := .i32 8) rfl), (.localTee rfl),
      (.localGet rfl), (.localGet rfl), (.gtU rfl)]
    apply Steps.cons (Step.select (maxWord firstMax 8 hfirst (by decide)))
    rw [hsecond]
    wasm_steps [(.localTee rfl), (.localGet rfl), (.localGet rfl)]
    exact Steps.refl _
  · intro before kind after member
    fin_cases member <;> rfl

private def headerStore (store : MachineStore α) (newCapacity base : UInt32) : MachineStore α :=
  { store with wasm := { store.wasm with mem := (store.wasm.mem.write32 driverBase newCapacity).write32 (driverBase + 4) base } }

private def reserveSuffixTrace : List StepKind :=
  [.instruction (.block 0 0 (blockAt func1 39))] ++
    ((blockAt func1 39).take 5).map StepKind.instruction ++
    (func1.drop 40).map StepKind.instruction ++ [.administrative .returnFromCall]

private theorem reserve_suffix (store : MachineStore α) (newCapacity base : UInt32)
    (caller : ThreadState α)
    (hglobal : globalAt? store 0 = some (.i32 reserveBase))
    (htag : store.wasm.mem.read32 (reserveBase + 4) = 0)
    (hptr : store.wasm.mem.read32 (reserveBase + 8) = base)
    (hphysical : driverBase.toNat + 12 ≤ store.wasm.mem.pages * 65536)
    (hostBytes : Config α → Nat → Config α → Nat) :
    CostedSteps (byteWork hostBytes)
      ⟨.running (reserveGrowCaller store newCapacity caller), store⟩ reserveSuffixTrace
      ⟨.running caller, stackStore (headerStore store newCapacity base) driverBase⟩ 20 := by
  apply Steps.with_unit_cost
  · unfold reserveSuffixTrace
    wasm_steps [.block, (.localGet rfl)]
    apply Steps.cons (Step.load32 (logicalAddress := reserveBase.toNat) (physicalAddress := reserveBase)
      rfl (by change reserveBase.toNat + 4 + 4 ≤ store.wasm.mem.pages * 65536
              exact (show reserveBase.toNat + 4 + 4 ≤ driverBase.toNat + 12 by decide).trans hphysical))
    rw [htag]
    wasm_steps [.const, (.ne (result := 1) rfl), (.brIf (by decide) rfl), (.localGet rfl)]
    apply Steps.cons (Step.load32 (logicalAddress := reserveBase.toNat) (physicalAddress := reserveBase)
      rfl (by change reserveBase.toNat + 8 + 4 ≤ store.wasm.mem.pages * 65536
              exact (show reserveBase.toNat + 8 + 4 ≤ driverBase.toNat + 12 by decide).trans hphysical))
    rw [hptr]
    wasm_steps [(.localSet rfl), (.localGet rfl), (.localGet rfl)]
    apply Steps.cons (Step.store32 (logicalAddress := driverBase.toNat) (physicalAddress := driverBase)
      rfl (by change driverBase.toNat + 0 + 4 ≤ store.wasm.mem.pages * 65536; omega))
    simp only [setMemory_eq, UInt32.add_zero]
    wasm_steps [(.localGet rfl), (.localGet rfl)]
    apply Steps.cons (Step.store32 (logicalAddress := driverBase.toNat) (physicalAddress := driverBase)
      rfl (by change driverBase.toNat + 4 + 4 ≤ store.wasm.mem.pages * 65536; omega))
    simp only [setMemory_eq]
    wasm_steps [(.localGet rfl), .const, .add]
    rw [show (16 : UInt32) + reserveBase = driverBase by decide]
    apply Steps.cons (Step.globalSet (by change (globalAt? store 0).isSome = true; rw [hglobal]; rfl))
    rw [setGlobal_zero_eq]
    exact Steps.single (Step.returnFromCallFallthrough rfl)
  · intro before kind after member
    fin_cases member <;> rfl

private theorem growResult_tag (store : MachineStore α) (oldCapacity oldPtr newCapacity base finish : UInt32) :
    (growFinalStore store (reserveBase + 4) oldCapacity oldPtr newCapacity base finish).wasm.mem.read32
      (reserveBase + 4) = 0 := by
  exact Mem.read32_write32_same _ _ _

private theorem growResult_pointer (store : MachineStore α) (oldCapacity oldPtr newCapacity base finish : UInt32) :
    (growFinalStore store (reserveBase + 4) oldCapacity oldPtr newCapacity base finish).wasm.mem.read32
      (reserveBase + 8) = base := by
  change ((((allocationStore store oldCapacity oldPtr base finish).wasm.mem.write32
    (reserveBase + 4 + 4) base).write32 (reserveBase + 4 + 8) newCapacity).write32
    (reserveBase + 4) 0).read32 (reserveBase + 8) = base
  rw [Mem.read32_write32_disjoint _ _ _ _ (by decide),
    Mem.read32_write32_disjoint _ _ _ _ (by decide),
    show reserveBase + 4 + 4 = reserveBase + 8 by decide,
    Mem.read32_write32_same]

private theorem growFinalStore_pages (store : MachineStore α)
    (result capacity ptr newCapacity base finish : UInt32) :
    (growFinalStore store result capacity ptr newCapacity base finish).wasm.mem.pages =
      max store.wasm.mem.pages (allocatorRequiredPages finish).toNat := by
  by_cases h : capacity = 0 <;>
    simp [growFinalStore, allocationStore, h, growResultStore,
      AllocatorExecution.finalStore, ReallocatorExecution.finalStore, AllocatorExecution.grownMemory, Mem.copy_pages]

private theorem growFinalStore_frame (store : MachineStore α)
    (result capacity ptr newCapacity base finish : UInt32) :
    (growFinalStore store result capacity ptr newCapacity base finish).runtime = store.runtime ∧
    (growFinalStore store result capacity ptr newCapacity base finish).wasm.globals = store.wasm.globals := by
  by_cases h : capacity = 0 <;>
    simp [growFinalStore, allocationStore, h, growResultStore,
      AllocatorExecution.finalStore, ReallocatorExecution.finalStore]

private theorem stackStore_global (store : MachineStore α) (value : UInt32)
    (hglobal : globalAt? store 0 = some (.i32 driverBase)) :
    globalAt? (stackStore store value) 0 = some (.i32 value) := by
  have h := hglobal
  simp only [globalAt?, canonicalGlobalIndex_zero] at h ⊢
  change (store.wasm.globals.globals.set 0 (.i32 value))[0]? = _
  cases hs : store.wasm.globals.globals with
  | nil => simp [hs] at h
  | cons a tail => simp

private theorem reserve_restored (store : MachineStore α)
    (capacity ptr newCapacity base finish : UInt32)
    (hglobal : globalAt? store 0 = some (.i32 driverBase)) :
    stackStore (headerStore
      (growFinalStore (stackStore store reserveBase) (reserveBase + 4)
        capacity ptr newCapacity base finish) newCapacity base) driverBase =
      finalStore store capacity ptr newCapacity base finish := by
  have hset : store.wasm.globals.globals.set 0 (.i32 driverBase) = store.wasm.globals.globals := by
    have h := hglobal
    simp only [globalAt?, canonicalGlobalIndex_zero] at h
    cases hs : store.wasm.globals.globals with
    | nil => simp
    | cons a tail =>
      have ha : a = .i32 driverBase := by simpa [hs] using h
      simp [ha]
  by_cases h : capacity = 0 <;>
    simp [stackStore, headerStore, growFinalStore, growResultStore, allocationStore,
      h, AllocatorExecution.finalStore, ReallocatorExecution.finalStore, finalStore,
      List.set_set, hset]

/-- Actual call 4 of the generated reserve wrapper. The initial classified
successful bump request determines the allocation; the conclusion constructs
its complete execution, including copying and physical memory growth. -/
theorem reserve_call_byteWork (store : MachineStore α)
    (length additional capacity ptr : UInt32) (frontier : Nat)
    (storedCursor base finish : UInt32) (caller : ThreadState α)
    (hmodule : store.runtime.currentModule = Project.Mergesort.module)
    (hcap : store.wasm.memoryCap store.runtime.currentModule 0 = Module.memoryHardCap)
    (hpages : store.wasm.mem.pages ≤ Module.memoryHardCap)
    (hglobal : globalAt? store 0 = some (.i32 driverBase))
    (hcapacity : store.wasm.mem.read32 driverBase = capacity)
    (hpointer : store.wasm.mem.read32 (driverBase + 4) = ptr)
    (hheader : driverBase.toNat + 12 ≤ store.wasm.mem.pages * 65536)
    (hfrontier : heapBase.toNat ≤ frontier)
    (hvalid : ({ size := selectedCapacity length.toNat additional.toNat capacity.toNat, alignment := 1 } : AllocLayout).Valid)
    (hclassify : classifyBump frontier
      { size := selectedCapacity length.toNat additional.toNat capacity.toNat, alignment := 1 } =
      .success base finish)
    (hcursor : store.wasm.mem.read32 allocatorCursor = storedCursor)
    (heffective : (if storedCursor ≠ 0 then storedCursor else heapBase) = UInt32.ofNat frontier)
    (hcursorBounds : allocatorCursor.toNat + 4 ≤ store.wasm.mem.pages * 65536)
    (hsource : ptr.toNat + capacity.toNat ≤ store.wasm.mem.pages * 65536)
    (hostBytes : Config α → Nat → Config α → Nat) :
    let newCapacity := UInt32.ofNat (selectedCapacity length.toNat additional.toNat capacity.toNat)
    ∃ trace, trace.length ≤ (if capacity = 0 then 185 else 203) ∧
      CostedSteps (byteWork hostBytes) (reserveCall store length additional caller)
        trace ⟨.running caller, finalStore store capacity ptr newCapacity base finish⟩
        (trace.length + capacity.toNat + 65536 *
          ((allocatorRequiredPages finish).toNat - store.wasm.mem.pages)) := by
  intro newCapacity
  have hnew := hvalid.2.2.2.2.2.1
  have hnewNat : newCapacity.toNat = selectedCapacity length.toNat additional.toNat capacity.toNat :=
    UInt32.toNat_ofNat_of_lt' hnew
  have hold : capacity.toNat < newCapacity.toNat := by
    rw [hnewNat]
    unfold selectedCapacity
    omega
  have first := reserve_prefix store length additional capacity ptr caller hmodule hglobal
    hcapacity hpointer hheader hnew hostBytes
  let lowered := stackStore store reserveBase
  let grown := growFinalStore lowered (reserveBase + 4) capacity ptr newCapacity base finish
  have hnewValid : ({ size := newCapacity.toNat, alignment := 1 } : AllocLayout).Valid := by
    simpa only [hnewNat] using hvalid
  have hnewClassify : classifyBump frontier { size := newCapacity.toNat, alignment := 1 } =
      .success base finish := by simpa only [hnewNat] using hclassify
  have hresult : (reserveBase + 4).toNat + 12 ≤ lowered.wasm.mem.pages * 65536 :=
    (show (reserveBase + 4).toNat + 12 ≤ driverBase.toNat + 12 by decide).trans hheader
  obtain ⟨growTrace, growBound, growRun⟩ := grow_call_byteWork lowered (reserveBase + 4)
    capacity ptr newCapacity frontier storedCursor base finish (reserveGrowCaller store newCapacity caller)
    hmodule hcap hpages hfrontier hnewValid hnewClassify hcursor heffective hcursorBounds hold hsource
    (by decide) hresult hostBytes
  have hframe := growFinalStore_frame lowered (reserveBase + 4) capacity ptr newCapacity base finish
  have hgrownGlobal : globalAt? grown 0 = some (.i32 reserveBase) := by
    change grown.wasm.globals.globals[0]? = _
    rw [hframe.2]
    exact stackStore_global store reserveBase hglobal
  have hgrownPhysical : driverBase.toNat + 12 ≤ grown.wasm.mem.pages * 65536 := by
    rw [growFinalStore_pages]
    exact hheader.trans (Nat.mul_le_mul_right 65536 (Nat.le_max_left _ _))
  have tail := reserve_suffix grown newCapacity base caller hgrownGlobal
    (growResult_tag lowered capacity ptr newCapacity base finish)
    (growResult_pointer lowered capacity ptr newCapacity base finish) hgrownPhysical hostBytes
  have hcaller : reserveGrowCaller grown newCapacity caller = reserveGrowCaller store newCapacity caller := by
    have hr : grown.runtime = store.runtime := hframe.1
    simp only [reserveGrowCaller, callerFrame, hr]
  rw [hcaller, reserve_restored store capacity ptr newCapacity base finish hglobal] at tail
  refine ⟨(reservePrefixTrace ++ growTrace) ++ reserveSuffixTrace, ?_, ?_⟩
  · simp only [List.length_append]
    change 46 + growTrace.length + 20 ≤ (if capacity = 0 then 185 else 203)
    split_ifs at growBound ⊢ <;> omega
  · have run := (first.trans growRun).trans tail
    convert run using 1
    simp only [List.length_append]
    change (46 + growTrace.length + 20) + capacity.toNat + 65536 *
      ((allocatorRequiredPages finish).toNat - store.wasm.mem.pages) =
      (46 + (growTrace.length + capacity.toNat + 65536 *
        ((allocatorRequiredPages finish).toNat - store.wasm.mem.pages))) + 20
    omega

end Project.Mergesort.ReserveCost
