/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.Itoa

open Wasm

def func0 : Wasm.Program :=
  [
  .globalGet 0,
  .const (32 : UInt32),
  .sub,
  .localSet 2,
  .localGet 2,
  .const (1 : UInt32),
  .store32 (4 : UInt32),
  .localGet 2,
  .localGet 0,
  .store64 (8 : UInt32),
  .block 0 0 [
    .loop 0 0 [
      .block 0 0 [
        .localGet 2,
        .load64 (8 : UInt32),
        .constI64 (10 : UInt64),
        .geUI64,
        .const (1 : UInt32),
        .and,
        .br_if 0,
        .localGet 2,
        .localGet 0,
        .store64 (16 : UInt32),
        .localGet 2,
        .localGet 2,
        .load32 (4 : UInt32),
        .store32 (28 : UInt32),
        .br 2
      ],
      .localGet 2,
      .localGet 2,
      .load64 (8 : UInt32),
      .constI64 (10 : UInt64),
      .divUI64,
      .store64 (8 : UInt32),
      .localGet 2,
      .localGet 2,
      .load32 (4 : UInt32),
      .const (1 : UInt32),
      .add,
      .store32 (4 : UInt32),
      .br 0
    ]
  ],
  .loop 0 1 [
    .block 0 0 [
      .localGet 2,
      .load32 (28 : UInt32),
      .const (0 : UInt32),
      .gtU,
      .const (1 : UInt32),
      .and,
      .br_if 0,
      .localGet 2,
      .load32 (4 : UInt32),
      .ret
    ],
    .localGet 2,
    .localGet 2,
    .load32 (28 : UInt32),
    .const (4294967295 : UInt32),
    .add,
    .store32 (28 : UInt32),
    .localGet 2,
    .load64 (16 : UInt32),
    .constI64 (10 : UInt64),
    .remUI64,
    .wrapI64,
    .localSet 3,
    .localGet 1,
    .localGet 2,
    .load32 (28 : UInt32),
    .add,
    .localGet 3,
    .const (48 : UInt32),
    .or,
    .store8 (0 : UInt32),
    .localGet 2,
    .localGet 2,
    .load64 (16 : UInt32),
    .constI64 (10 : UInt64),
    .divUI64,
    .store64 (16 : UInt32),
    .br 0
  ]
]

def func0Def : Wasm.Function :=
  { params := [.i64, .i32], locals := [.i32, .i32], body := func0, results := [.i32] }

/-- export: itoa -/
def func1 : Wasm.Program :=
  [
  .localGet 0,
  .localGet 1,
  .call 0,
  .ret
]

def func1Def : Wasm.Function :=
  { params := [.i64, .i32], locals := [], body := func1, results := [.i32] }

def «module» : Wasm.Module :=
{
  imports := [],
  funcs := [
    func0Def,
    func1Def
  ],
  exports := [
    { name := "itoa", funcIdx := 1 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1048576 : UInt32) }
  ],
  types := [
    { params := [.i64, .i32], results := [.i32] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.Itoa
