/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.NumInteger

open Wasm

def func0 : Wasm.Program :=
  [
  .globalGet 0,
  .const (16 : UInt32),
  .sub,
  .localSet 2,
  .localGet 2,
  .globalSet 0,
  .localGet 2,
  .localGet 0,
  .store64 (0 : UInt32),
  .localGet 2,
  .localGet 1,
  .store64 (8 : UInt32),
  .localGet 2,
  .localGet 2,
  .const (8 : UInt32),
  .add,
  .call 1,
  .localSet 3,
  .localGet 2,
  .const (16 : UInt32),
  .add,
  .globalSet 0,
  .localGet 3,
  .ret
]

def func0Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i32, .i64], body := func0, results := [.i64] }

def func1 : Wasm.Program :=
  [
  .globalGet 0,
  .const (128 : UInt32),
  .sub,
  .localSet 2,
  .localGet 2,
  .localGet 0,
  .store32 (36 : UInt32),
  .localGet 2,
  .localGet 1,
  .store32 (40 : UInt32),
  .localGet 2,
  .localGet 0,
  .load64 (0 : UInt32),
  .store64 (16 : UInt32),
  .localGet 2,
  .localGet 1,
  .load64 (0 : UInt32),
  .store64 (24 : UInt32),
  .block 0 0 [
    .block 0 0 [
      .block 0 0 [
        .localGet 2,
        .load64 (16 : UInt32),
        .constI64 (0 : UInt64),
        .eqI64,
        .const (1 : UInt32),
        .and,
        .br_if 0,
        .localGet 2,
        .load64 (24 : UInt32),
        .constI64 (0 : UInt64),
        .eqI64,
        .const (1 : UInt32),
        .and,
        .eqz,
        .br_if 1
      ],
      .localGet 2,
      .localGet 2,
      .load64 (16 : UInt32),
      .localGet 2,
      .load64 (24 : UInt32),
      .orI64,
      .store64 (8 : UInt32),
      .br 1
    ],
    .localGet 2,
    .load64 (16 : UInt32),
    .localGet 2,
    .load64 (24 : UInt32),
    .orI64,
    .localSet 3,
    .localGet 2,
    .localGet 3,
    .store64 (112 : UInt32),
    .localGet 2,
    .localGet 3,
    .ctzI64,
    .wrapI64,
    .store32 (124 : UInt32),
    .localGet 2,
    .load32 (124 : UInt32),
    .localSet 4,
    .localGet 2,
    .localGet 4,
    .store32 (44 : UInt32),
    .localGet 2,
    .load64 (16 : UInt32),
    .localSet 5,
    .localGet 2,
    .localGet 5,
    .store64 (96 : UInt32),
    .localGet 2,
    .localGet 5,
    .ctzI64,
    .wrapI64,
    .store32 (108 : UInt32),
    .localGet 2,
    .load32 (108 : UInt32),
    .localSet 6,
    .localGet 2,
    .localGet 2,
    .load64 (16 : UInt32),
    .localGet 6,
    .const (63 : UInt32),
    .and,
    .extendUI32,
    .shrUI64,
    .store64 (16 : UInt32),
    .localGet 2,
    .load64 (24 : UInt32),
    .localSet 7,
    .localGet 2,
    .localGet 7,
    .store64 (80 : UInt32),
    .localGet 2,
    .localGet 7,
    .ctzI64,
    .wrapI64,
    .store32 (92 : UInt32),
    .localGet 2,
    .load32 (92 : UInt32),
    .localSet 8,
    .localGet 2,
    .localGet 2,
    .load64 (24 : UInt32),
    .localGet 8,
    .const (63 : UInt32),
    .and,
    .extendUI32,
    .shrUI64,
    .store64 (24 : UInt32),
    .loop 0 0 [
      .block 0 0 [
        .localGet 2,
        .load64 (16 : UInt32),
        .localGet 2,
        .load64 (24 : UInt32),
        .neI64,
        .const (1 : UInt32),
        .and,
        .br_if 0,
        .localGet 2,
        .localGet 2,
        .load64 (16 : UInt32),
        .localGet 4,
        .const (63 : UInt32),
        .and,
        .extendUI32,
        .shlI64,
        .store64 (8 : UInt32),
        .br 2
      ],
      .block 0 0 [
        .localGet 2,
        .load64 (16 : UInt32),
        .localGet 2,
        .load64 (24 : UInt32),
        .gtUI64,
        .const (1 : UInt32),
        .and,
        .br_if 0,
        .localGet 2,
        .load64 (16 : UInt32),
        .localSet 9,
        .localGet 2,
        .localGet 2,
        .load64 (24 : UInt32),
        .localGet 9,
        .subI64,
        .store64 (24 : UInt32),
        .localGet 2,
        .load64 (24 : UInt32),
        .localSet 10,
        .localGet 2,
        .localGet 10,
        .store64 (64 : UInt32),
        .localGet 2,
        .localGet 10,
        .ctzI64,
        .wrapI64,
        .store32 (76 : UInt32),
        .localGet 2,
        .load32 (76 : UInt32),
        .localSet 11,
        .localGet 2,
        .localGet 2,
        .load64 (24 : UInt32),
        .localGet 11,
        .const (63 : UInt32),
        .and,
        .extendUI32,
        .shrUI64,
        .store64 (24 : UInt32),
        .br 1
      ],
      .localGet 2,
      .load64 (24 : UInt32),
      .localSet 12,
      .localGet 2,
      .localGet 2,
      .load64 (16 : UInt32),
      .localGet 12,
      .subI64,
      .store64 (16 : UInt32),
      .localGet 2,
      .load64 (16 : UInt32),
      .localSet 13,
      .localGet 2,
      .localGet 13,
      .store64 (48 : UInt32),
      .localGet 2,
      .localGet 13,
      .ctzI64,
      .wrapI64,
      .store32 (60 : UInt32),
      .localGet 2,
      .load32 (60 : UInt32),
      .localSet 14,
      .localGet 2,
      .localGet 2,
      .load64 (16 : UInt32),
      .localGet 14,
      .const (63 : UInt32),
      .and,
      .extendUI32,
      .shrUI64,
      .store64 (16 : UInt32),
      .br 0
    ]
  ],
  .localGet 2,
  .load64 (8 : UInt32),
  .ret
]

def func1Def : Wasm.Function :=
  { params := [.i32, .i32], locals := [.i32, .i64, .i32, .i64, .i32, .i64, .i32, .i64, .i64, .i32, .i64, .i64, .i32], body := func1, results := [.i64] }

/-- export: gcd_u64 -/
def func2 : Wasm.Program :=
  [
  .globalGet 0,
  .const (16 : UInt32),
  .sub,
  .localSet 2,
  .localGet 2,
  .globalSet 0,
  .localGet 2,
  .localGet 0,
  .store64 (0 : UInt32),
  .localGet 2,
  .localGet 1,
  .store64 (8 : UInt32),
  .localGet 0,
  .localGet 1,
  .call 0,
  .localSet 3,
  .localGet 2,
  .const (16 : UInt32),
  .add,
  .globalSet 0,
  .localGet 3,
  .ret
]

def func2Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i32, .i64], body := func2, results := [.i64] }

def «module» : Wasm.Module :=
{
  imports := [],
  funcs := [
    func0Def,
    func1Def,
    func2Def
  ],
  exports := [
    { name := "gcd_u64", funcIdx := 2 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) }
  ],
  types := [
    { params := [.i64, .i64], results := [.i64] },
    { params := [.i32, .i32], results := [.i64] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.NumInteger
