/-
  AUTO-GENERATED by `lake exe verifier check`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.XorSum

open Wasm

/-- export: xor_sum -/
def func0 : Wasm.Program :=
  [
  .const (0 : UInt32),
  .localSet 2,
  .block 0 0 [
    .localGet 1,
    .eqz,
    .br_if 0,
    .loop 0 0 [
      .localGet 0,
      .load32 (0 : UInt32),
      .localGet 2,
      .xor,
      .localSet 2,
      .localGet 0,
      .const (4 : UInt32),
      .add,
      .localSet 0,
      .localGet 1,
      .const (4294967295 : UInt32),
      .add,
      .localSet 1,
      .localGet 1,
      .br_if 0
    ]
  ],
  .localGet 2
]

def «module» : Wasm.Module :=
{
  imports := [],
  funcs := [
    { params := [.i32, .i32], locals := [.i32], body := func0, results := [.i32] }
  ],
  exports := [
    { name := "xor_sum", funcIdx := 0 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) }
  ],
  types := [
    { params := [.i32, .i32], results := [.i32] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.XorSum
