/-
  AUTO-GENERATED by `lake exe verifier check`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.ReverseInplace

open Wasm

/-- export: reverse_inplace -/
def func0 : Wasm.Program :=
  [
  .block 0 0 [
    .localGet 1,
    .const (2 : UInt32),
    .ltU,
    .br_if 0,
    .localGet 1,
    .const (4294967295 : UInt32),
    .add,
    .localSet 2,
    .localGet 1,
    .const (2 : UInt32),
    .shl,
    .localGet 0,
    .add,
    .const (4294967292 : UInt32),
    .add,
    .localSet 1,
    .const (1 : UInt32),
    .localSet 3,
    .loop 0 0 [
      .localGet 0,
      .load32 (0 : UInt32),
      .localSet 4,
      .localGet 0,
      .localGet 1,
      .load32 (0 : UInt32),
      .store32 (0 : UInt32),
      .localGet 1,
      .localGet 4,
      .store32 (0 : UInt32),
      .localGet 0,
      .const (4 : UInt32),
      .add,
      .localSet 0,
      .localGet 1,
      .const (4294967292 : UInt32),
      .add,
      .localSet 1,
      .localGet 3,
      .localGet 2,
      .const (4294967295 : UInt32),
      .add,
      .localSet 2,
      .localGet 2,
      .ltU,
      .localSet 4,
      .localGet 3,
      .const (1 : UInt32),
      .add,
      .localSet 3,
      .localGet 4,
      .br_if 0
    ]
  ]
]

def «module» : Wasm.Module :=
{
  imports := [],
  funcs := [
    { params := [.i32, .i32], locals := [.i32, .i32, .i32], body := func0, results := [] }
  ],
  exports := [
    { name := "reverse_inplace", funcIdx := 0 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) }
  ],
  types := [
    { params := [.i32, .i32], results := [] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.ReverseInplace
