/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.Memchr

open Wasm

/-- export: memchr -/
def func0 : Wasm.Program :=
  [
  .const (0 : UInt32),
  .localSet 3,
  .block 0 0 [
    .localGet 1,
    .eqz,
    .br_if 0,
    .loop 0 0 [
      .localGet 0,
      .localGet 3,
      .add,
      .load8U (0 : UInt32),
      .localGet 2,
      .eq,
      .br_if 1,
      .localGet 1,
      .localGet 3,
      .const (1 : UInt32),
      .add,
      .localSet 3,
      .localGet 3,
      .ne,
      .br_if 0
    ],
    .localGet 1,
    .localSet 3
  ],
  .localGet 3
]

def func0Def : Wasm.Function :=
  { params := [.i32, .i32, .i32], locals := [.i32], body := func0, results := [.i32] }

def «module» : Wasm.Module :=
{
  imports := [],
  funcs := [
    func0Def
  ],
  exports := [
    { name := "memchr", funcIdx := 0 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1048576 : UInt32) }
  ],
  types := [
    { params := [.i32, .i32, .i32], results := [.i32] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.Memchr
