/-
  AUTO-GENERATED by `lake exe verifier check`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.IsPrime

open Wasm

def func0 : Wasm.Program :=
  [
  .block 0 0 [
    .localGet 0,
    .const (2 : UInt32),
    .geU,
    .br_if 0,
    .const (0 : UInt32),
    .ret
  ],
  .block 0 0 [
    .block 0 0 [
      .localGet 0,
      .const (4 : UInt32),
      .geU,
      .br_if 0,
      .const (1 : UInt32),
      .localSet 1,
      .br 1
    ],
    .localGet 0,
    .const (1 : UInt32),
    .shrU,
    .localSet 2,
    .const (2 : UInt32),
    .localSet 3,
    .loop 0 0 [
      .localGet 0,
      .localGet 3,
      .remU,
      .localSet 4,
      .localGet 4,
      .const (0 : UInt32),
      .ne,
      .localSet 1,
      .localGet 2,
      .localGet 3,
      .eq,
      .br_if 1,
      .localGet 3,
      .const (1 : UInt32),
      .add,
      .localSet 3,
      .localGet 4,
      .br_if 0
    ]
  ],
  .localGet 1
]

def func1 : Wasm.Program :=
  [
  .block 0 0 [
    .localGet 0,
    .const (2 : UInt32),
    .geU,
    .br_if 0,
    .const (0 : UInt32),
    .ret
  ],
  .block 0 0 [
    .block 0 0 [
      .localGet 0,
      .const (2 : UInt32),
      .ne,
      .br_if 0,
      .const (1 : UInt32),
      .localSet 1,
      .br 1
    ],
    .const (3 : UInt32),
    .localSet 2,
    .loop 0 0 [
      .localGet 0,
      .localGet 2,
      .const (4294967295 : UInt32),
      .add,
      .remU,
      .localSet 3,
      .localGet 3,
      .const (0 : UInt32),
      .ne,
      .localSet 1,
      .localGet 3,
      .eqz,
      .br_if 1,
      .localGet 0,
      .localGet 2,
      .ne,
      .localSet 3,
      .localGet 2,
      .const (1 : UInt32),
      .add,
      .localSet 2,
      .localGet 3,
      .br_if 0
    ]
  ],
  .localGet 1
]

def func2 : Wasm.Program :=
  [
  .block 0 0 [
    .localGet 0,
    .call 1,
    .localGet 0,
    .call 0,
    .ne,
    .br_if 0,
    .ret
  ],
  .unreachable
]

/-- export: check -/
def func3 : Wasm.Program :=
  [
  .localGet 0,
  .call 2
]

def «module» : Wasm.Module :=
{
  funcs := [
    { params := [.i32], locals := [.i32, .i32, .i32, .i32], body := func0, results := [.i32] },
    { params := [.i32], locals := [.i32, .i32, .i32], body := func1, results := [.i32] },
    { params := [.i32], locals := [], body := func2, results := [] },
    { params := [.i32], locals := [], body := func3, results := [] }
  ],
  exports := [
    { name := "check", funcIdx := 3 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) }
  ],
  types := [
    { params := [.i32], results := [.i32] },
    { params := [.i32], results := [] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.IsPrime
