/-
  AUTO-GENERATED by `lake exe verifier check`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.HostCounter

open Wasm

def func0 : Wasm.Program :=
  [
  .block 0 0 [
    .call 0,
    .const (9 : UInt32),
    .gtU,
    .br_if 0,
    .call 1
  ]
]

def «module» : Wasm.Module :=
{
  imports := [
    { «module» := "env", name := "host_get", params := [], results := [.i32] },
    { «module» := "env", name := "host_inc", params := [], results := [] }
  ],
  funcs := [
    { params := [], locals := [], body := func0, results := [] }
  ],
  exports := [
    { name := "step", funcIdx := 2 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) }
  ],
  types := [
    { params := [], results := [.i32] },
    { params := [], results := [] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.HostCounter
