/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.HostCounter

open Wasm

def func0 : Wasm.Program :=
  [
  .block 0 0 [
    .call 0,
    .const (10 : UInt32),
    .ltU,
    .const (1 : UInt32),
    .and,
    .eqz,
    .br_if 0,
    .call 1
  ],
  .ret
]

def func0Def : Wasm.Function :=
  { params := [], locals := [], body := func0, results := [] }

def func1 : Wasm.Program :=
  [
  .call 2,
  .ret
]

def func1Def : Wasm.Function :=
  { params := [], locals := [], body := func1, results := [] }

def «module» : Wasm.Module :=
{
  imports := [
    { «module» := "env", name := "host_get", params := [], results := [.i32] },
    { «module» := "env", name := "host_inc", params := [], results := [] }
  ],
  funcs := [
    func0Def,
    func1Def
  ],
  exports := [
    { name := "step", funcIdx := 3 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) }
  ],
  types := [
    { params := [], results := [.i32] },
    { params := [], results := [] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.HostCounter
