/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.IsEven

open Wasm

/-- export: is_even -/
def func0 : Wasm.Program :=
  [
  .localGet 0,
  .const (1 : UInt32),
  .and,
  .eqz
]

def func0Def : Wasm.Function :=
  { params := [.i32], locals := [], body := func0, results := [.i32] }

def «module» : Wasm.Module :=
{
  imports := [],
  funcs := [
    func0Def
  ],
  exports := [
    { name := "is_even", funcIdx := 0 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) }
  ],
  types := [
    { params := [.i32], results := [.i32] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.IsEven
