import Project.EncodeDecode.Spec
import Project.EncodeDecodeTests.Spec
import Project.NumInteger.Spec
import Project.RustArray.Spec
import Project.RustArrayTests.Spec
import Project.RustU64.Spec
import Project.RustU64Tests.Spec
import Project.SwapElements.Spec
import Project.TotalVariation.Spec
