/-
  AUTO-GENERATED by `lake exe verifier check`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.RustOption

open Wasm

/-- export: filter_positive -/
def func0 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 (9223372036854775808 : UInt64),
  .localGet 0,
  .constI64 (0 : UInt64),
  .gtSI64,
  .select
]

/-- export: is_some -/
def func1 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 (9223372036854775808 : UInt64),
  .neI64
]

/-- export: map_add -/
def func2 : Wasm.Program :=
  [
  .constI64 (9223372036854775808 : UInt64),
  .localGet 1,
  .localGet 0,
  .addI64,
  .localGet 0,
  .constI64 (9223372036854775808 : UInt64),
  .eqI64,
  .select
]

/-- exports: or, unwrap_or -/
def func3 : Wasm.Program :=
  [
  .localGet 1,
  .localGet 0,
  .localGet 0,
  .constI64 (9223372036854775808 : UInt64),
  .eqI64,
  .select
]

/-- export: unwrap_or_default -/
def func4 : Wasm.Program :=
  [
  .constI64 (0 : UInt64),
  .localGet 0,
  .localGet 0,
  .constI64 (9223372036854775808 : UInt64),
  .eqI64,
  .select
]

/-- export: wrap -/
def func5 : Wasm.Program :=
  [
  .localGet 0
]

def «module» : Wasm.Module :=
{
  funcs := [
    { params := [.i64], locals := [], body := func0, results := [.i64] },
    { params := [.i64], locals := [], body := func1, results := [.i32] },
    { params := [.i64, .i64], locals := [], body := func2, results := [.i64] },
    { params := [.i64, .i64], locals := [], body := func3, results := [.i64] },
    { params := [.i64], locals := [], body := func4, results := [.i64] },
    { params := [.i64], locals := [], body := func5, results := [.i64] }
  ],
  exports := [
    { name := "filter_positive", funcIdx := 0 },
    { name := "is_some", funcIdx := 1 },
    { name := "map_add", funcIdx := 2 },
    { name := "or", funcIdx := 3 },
    { name := "unwrap_or_default", funcIdx := 4 },
    { name := "wrap", funcIdx := 5 },
    { name := "unwrap_or", funcIdx := 3 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) },
    { type := .i32, init := .i32 (1048576 : UInt32) }
  ]
}

end Project.RustOption
