/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.RustU64Tests

open Wasm

/-- export: mul -/
def func0 : Wasm.Program :=
  [
  .localGet 0,
  .localGet 1,
  .mulI64,
  .ret
]

def func0Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [], body := func0, results := [.i64] }

/-- export: mul_prod3 -/
def func1 : Wasm.Program :=
  [
  .localGet 0,
  .localGet 1,
  .call 0,
  .localGet 2,
  .call 0,
  .ret
]

def func1Def : Wasm.Function :=
  { params := [.i64, .i64, .i64], locals := [], body := func1, results := [.i64] }

def «module» : Wasm.Module :=
{
  imports := [],
  funcs := [
    func0Def,
    func1Def
  ],
  exports := [
    { name := "mul", funcIdx := 0 },
    { name := "mul_prod3", funcIdx := 1 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1048576 : UInt32) }
  ],
  types := [
    { params := [.i64, .i64], results := [.i64] },
    { params := [.i64, .i64, .i64], results := [.i64] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.RustU64Tests
