/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.EncodeDecode

open Wasm

def func0 : Wasm.Program :=
  [
  .globalGet 0,
  .const (16 : UInt32),
  .sub,
  .localSet 2,
  .localGet 2,
  .localGet 0,
  .load32 (0 : UInt32),
  .store32 (8 : UInt32),
  .localGet 2,
  .localGet 2,
  .load32 (8 : UInt32),
  .store32 (12 : UInt32),
  .localGet 2,
  .load32 (12 : UInt32),
  .ret
]

def func0Def : Wasm.Function :=
  { params := [.i32, .i32], locals := [.i32], body := func0, results := [.i32] }

def func1 : Wasm.Program :=
  [
  .globalGet 0,
  .const (16 : UInt32),
  .sub,
  .localSet 3,
  .localGet 3,
  .localGet 1,
  .store32 (12 : UInt32),
  .localGet 0,
  .localGet 3,
  .load32 (12 : UInt32),
  .store32 (0 : UInt32),
  .ret
]

def func1Def : Wasm.Function :=
  { params := [.i32, .i32, .i32], locals := [.i32], body := func1, results := [] }

/-- export: decode -/
def func2 : Wasm.Program :=
  [
  .globalGet 0,
  .const (16 : UInt32),
  .sub,
  .localSet 4,
  .localGet 4,
  .globalSet 0,
  .block 0 0 [
    .block 0 0 [
      .block 0 0 [
        .block 0 0 [
          .block 0 0 [
            .block 0 0 [
              .localGet 1,
              .const (4 : UInt32),
              .ltU,
              .const (1 : UInt32),
              .and,
              .br_if 0,
              .localGet 0,
              .const (1048608 : UInt32),
              .call 0,
              .localSet 5,
              .localGet 5,
              .localGet 1,
              .const (4 : UInt32),
              .sub,
              .gtU,
              .const (1 : UInt32),
              .and,
              .br_if 2,
              .br 1
            ],
            .localGet 4,
            .constI64 (18446744073709551615 : UInt64),
            .store64 (8 : UInt32),
            .br 4
          ],
          .localGet 5,
          .localGet 3,
          .gtU,
          .const (1 : UInt32),
          .and,
          .br_if 2,
          .br 1
        ],
        .localGet 4,
        .constI64 (18446744073709551614 : UInt64),
        .store64 (8 : UInt32),
        .br 2
      ],
      .localGet 0,
      .const (4 : UInt32),
      .add,
      .localSet 6,
      .block 0 0 [
        .localGet 5,
        .eqz,
        .br_if 0,
        .localGet 2,
        .localGet 6,
        .localGet 5,
        .memoryCopy
      ],
      .localGet 4,
      .localGet 5,
      .extendUI32,
      .store64 (8 : UInt32),
      .br 1
    ],
    .localGet 4,
    .constI64 (18446744073709551613 : UInt64),
    .store64 (8 : UInt32)
  ],
  .localGet 4,
  .load64 (8 : UInt32),
  .localSet 7,
  .localGet 4,
  .const (16 : UInt32),
  .add,
  .globalSet 0,
  .localGet 7,
  .ret
]

def func2Def : Wasm.Function :=
  { params := [.i32, .i32, .i32, .i32], locals := [.i32, .i32, .i32, .i64], body := func2, results := [.i64] }

/-- export: encode -/
def func3 : Wasm.Program :=
  [
  .localGet 2,
  .localGet 1,
  .const (1048624 : UInt32),
  .call 1,
  .localGet 2,
  .const (4 : UInt32),
  .add,
  .localSet 3,
  .block 0 0 [
    .localGet 1,
    .eqz,
    .br_if 0,
    .localGet 3,
    .localGet 0,
    .localGet 1,
    .memoryCopy
  ],
  .localGet 1,
  .const (4 : UInt32),
  .add,
  .ret
]

def func3Def : Wasm.Function :=
  { params := [.i32, .i32, .i32], locals := [.i32], body := func3, results := [.i32] }

def «module» : Wasm.Module :=
{
  imports := [],
  funcs := [
    func0Def,
    func1Def,
    func2Def,
    func3Def
  ],
  exports := [
    { name := "decode", funcIdx := 2 },
    { name := "encode", funcIdx := 3 }
  ],
  memory := some { pagesMin := (17 : UInt32), pagesMax := none, data := [
    { offset := some (1048576 : UInt32), bytes := [(101 : UInt8), (110 : UInt8), (99 : UInt8), (111 : UInt8), (100 : UInt8), (101 : UInt8), (95 : UInt8), (100 : UInt8), (101 : UInt8), (99 : UInt8), (111 : UInt8), (100 : UInt8), (101 : UInt8), (47 : UInt8), (115 : UInt8), (114 : UInt8), (99 : UInt8), (47 : UInt8), (101 : UInt8), (120 : UInt8), (112 : UInt8), (111 : UInt8), (114 : UInt8), (116 : UInt8), (115 : UInt8), (46 : UInt8), (114 : UInt8), (115 : UInt8), (0 : UInt8), (0 : UInt8), (0 : UInt8), (0 : UInt8), (0 : UInt8), (0 : UInt8), (16 : UInt8), (0 : UInt8), (28 : UInt8), (0 : UInt8), (0 : UInt8), (0 : UInt8), (37 : UInt8), (0 : UInt8), (0 : UInt8), (0 : UInt8), (22 : UInt8), (0 : UInt8), (0 : UInt8), (0 : UInt8), (0 : UInt8), (0 : UInt8), (16 : UInt8), (0 : UInt8), (28 : UInt8), (0 : UInt8), (0 : UInt8), (0 : UInt8), (17 : UInt8), (0 : UInt8), (0 : UInt8), (0 : UInt8), (9 : UInt8), (0 : UInt8), (0 : UInt8), (0 : UInt8)] }
  ] },
  globals := [
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1048640 : UInt32) },
    { init := .i32 (1048640 : UInt32) }
  ],
  types := [
    { params := [.i32, .i32], results := [.i32] },
    { params := [.i32, .i32, .i32], results := [] },
    { params := [.i32, .i32, .i32, .i32], results := [.i64] },
    { params := [.i32, .i32, .i32], results := [.i32] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.EncodeDecode
