/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.RustStd

open Wasm

def func0 : Wasm.Program :=
  [
  .globalGet 0,
  .const (16 : UInt32),
  .sub,
  .localSet 2,
  .block 0 0 [
    .block 0 0 [
      .localGet 0,
      .localGet 1,
      .ltUI64,
      .const (1 : UInt32),
      .and,
      .br_if 0,
      .localGet 2,
      .localGet 0,
      .localGet 1,
      .subI64,
      .store64 (8 : UInt32),
      .br 1
    ],
    .localGet 2,
    .localGet 1,
    .localGet 0,
    .subI64,
    .store64 (8 : UInt32)
  ],
  .localGet 2,
  .load64 (8 : UInt32),
  .ret
]

def func0Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i32], body := func0, results := [.i64] }

/-- export: count_ones -/
def func1 : Wasm.Program :=
  [
  .globalGet 0,
  .const (16 : UInt32),
  .sub,
  .localSet 1,
  .localGet 1,
  .localGet 0,
  .popcntI64,
  .wrapI64,
  .store32 (12 : UInt32),
  .localGet 1,
  .load32 (12 : UInt32),
  .ret
]

def func1Def : Wasm.Function :=
  { params := [.i64], locals := [.i32], body := func1, results := [.i32] }

/-- export: entrypoint -/
def func2 : Wasm.Program :=
  [
  .localGet 0,
  .call 1,
  .drop,
  .localGet 0,
  .localGet 1,
  .call 3,
  .drop,
  .ret
]

def func2Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [], body := func2, results := [] }

/-- export: u64_abs_diff -/
def func3 : Wasm.Program :=
  [
  .localGet 0,
  .localGet 1,
  .call 0,
  .ret
]

def func3Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [], body := func3, results := [.i64] }

def «module» : Wasm.Module :=
{
  imports := [],
  funcs := [
    func0Def,
    func1Def,
    func2Def,
    func3Def
  ],
  exports := [
    { name := "count_ones", funcIdx := 1 },
    { name := "entrypoint", funcIdx := 2 },
    { name := "u64_abs_diff", funcIdx := 3 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1048576 : UInt32) },
    { init := .i32 (1048576 : UInt32) }
  ],
  types := [
    { params := [.i64, .i64], results := [.i64] },
    { params := [.i64], results := [.i32] },
    { params := [.i64, .i64], results := [] }
  ],
  tables := [
    { min := 1, max := some 1, elemType := .funcref }
  ],
  elements := []
}

end Project.RustStd
