import CodeLib.Tactics.Rule
import CodeLib.SepLogic.SmallStepTotalLifting
import CodeLib.SepLogic.SmallStepTotalLiftingBytes
import CodeLib.SepLogic.SmallStepLifting

/-!
# Wasm TWP and WP rule registry

The `@[wasm_rule]` / `@[wasm_mem_rule]` table that `wasm_pure`, `wasm_pures` and
`wasm_mem` dispatch on is **not** written here. Every rule is registered at its
definition site, so the table cannot drift from the rules:

* rules generated by `wasm_twp_pure_rule` / `wasm_wp_pure_rule` register
  themselves under the instruction constructor they retire
  (`CodeLib.Tactics.wasmPureRuleAttr?`);
* hand-written step rules (locals, branches, blocks, loads, stores, globals)
  carry an explicit `@[wasm_rule …]` / `@[wasm_mem_rule …]` attribute;
* the generic `scalarFloat*` rules, whose instruction is a variable, are
  registered for each instruction they serve right after their definitions.

This module only gathers the files that define rules, so importing it gives
the complete table. `CodeLib.Tactics.Test` checks that every step rule whose
conclusion retires a concrete instruction is registered (or explicitly
listed as intentionally unregistered).
-/

-- Forward syntax declaration so Pure.lean can quote `wasm_mem` before Mem.lean
-- defines its elaborator.  The `@[tactic wasm_mem]` attribute in Mem.lean wires
-- up the implementation; at Pure.lean's compile time, only the syntax is needed.
syntax (name := wasm_mem) "wasm_mem" ("using" "[" term,* "]")? : tactic
